# Generated by Django 5.0.4 on 2024-06-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bitcaster", "0002_user_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Browser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bitcaster.assignment",),
        ),
    ]
