# Generated by Django 5.2.9 on 2025-12-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bitcaster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Browser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bitcaster.assignment",),
        ),
    ]
