# This is used by the action https://github.com/dorny/paths-filter
docker: &docker
  - added|modified: './docker/**/*'
  - added|modified: './docker/*'

dependencies: &dependencies
  - 'uv.lock'
  - 'pyproject.toml'

actions: &actions
  - added|modified: './.github/**/*'

python: &python
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'manage.py'

changelog:
  - added|modified: 'changes/**'
  - 'CHANGELOG.md'

mypy:
  - *python
  - 'mypy.ini'

run_tests:
  - *actions
  - *python
  - *docker
  - *dependencies
  - 'pytest.ini'
  - 'tox.ini'

package: &package
  - *python
  - *dependencies

dockerize:
  - *package
  - *docker
  - '.github/workflows/test.yml'
  - '.github/workflows/dockerize.yml'

migrations:
  - added|modified: 'src/**/migrations/*'

code_settings: &code_settings
  - '.pre-commit-config.yaml'
  - '.semgrep.yaml'
  - '.semgrepignore'
  - '.trivyignore'
  - 'bandit.yaml'
  - 'djlint.toml'
  - 'mypy.ini'
  - 'pyproject.toml'
  - 'pytest.ini'
  - 'ruff.toml'
  - 'tox.ini'
  - 'transifex.yml'
  - 'trivy.yaml'


lint:
  - *python
  - *code_settings

docs:
  - added|modified: './docs/**/*'
  - modified: './properdocs.yml'
  - added|modified: './tests/docs/**'
  - modified: './src/bitcaster/config/__init__.py'
  - modified: './.github/workflows/docs.yml'
  - modified: './.github/file-filters.yml'
