# This is used by the action https://github.com/dorny/paths-filter
docker: &docker
  - added|modified: './docker/**/*'
  - added|modified: './docker/*'

dependencies: &dependencies
  - 'pdm.lock'
  - 'pyproject.toml'

python: &python
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'manage.py'

changelog:
  - added|modified: 'changes/**'
  - 'CHANGELOG.md'

mypy:
  - *python
  - 'mypy.ini'

build:
  - *docker
  - *dependencies

run_tests:
  - *python
  - *docker
  - *dependencies
  - 'pytest.ini'

migrations:
  - added|modified: 'src/**/migrations/*'

lint:
  -  *python
  - '.flake8'
  - 'pyproject.toml'
