exclude: '^$'
fail_fast: false
repos:
-   repo: local
    hooks:
      - id: isort
        args:
            - --check-only
        name: isort
        entry: isort
        language: system
        types: [python]

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: debug-statements
        exclude: (_plugin_template|python_twitter)
    -   id: end-of-file-fixer
    -   id: flake8
        include: (src|tests)
        exclude: /(_plugin_template|python_twitter|migrations)/
        args:
        - src/
        - tests/
    -   id: check-merge-conflict
    -   id: check-case-conflict

-   repo: https://github.com/saxix/pch
    rev: fc387f4
    hooks:
    -   id: check-version-release-match
        args:
        - --pythonpath=src
        - --package=etools_datamart
        stages: [push]
    -   id: check-untracked
        args:
        - src
        - tests
        stages: [push]
    -   id: check-forbidden
        args:
        - -p
        - \.showbrowser\(
