x-common: &common
  build:
    context: .
    dockerfile: docker/Dockerfile
    target: dist
  platform: linux/amd64
  environment:
    - ADMIN_EMAIL=admin@gmail.com
    - ADMIN_PASSWORD=123
    - CACHE_URL=redis://redis:6379/1?client_class=django_redis.client.DefaultClient
    - CELERY_BROKER_URL=redis://redis:6379/9
    - CELERY_TASK_ALWAYS_EAGER=False
    - CSRF_COOKIE_SECURE=False
    - DATABASE_URL=postgres://bitcaster:password@db:5432/bitcaster
    - PYTHONPATH=/code/app/src:/code/__pypackages__/3.12/lib
    - SECRET_KEY=super_secret_key_just_for_development
    - SECURE_SSL_REDIRECT=False
    - SESSION_COOKIE_DOMAIN=
    - SESSION_COOKIE_SECURE=False
    - SOCIAL_AUTH_REDIRECT_IS_HTTPS=False
    - STATIC_ROOT=/var/bitcaster/static
  volumes:
    - static_storage:/var/bitcaster/static
    - .:/code/app
    - ./docker/conf:/conf
    - ./docker/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
  restart: unless-stopped
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  app:
    <<: *common
    container_name: bitcaster_bitcaster
    ports:
      - 8000:8000
#    command: ["run"]
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  worker:
    <<: *common
    command: ["worker"]
    container_name: bitcaster_worker
    depends_on:
      db:
        condition: service_healthy
  beat:
    <<: *common
    container_name: bitcaster_beat
    command: ["beat"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: bitcaster_db
    user: postgres
    environment:
      - PGUSER=bitcaster
      - POSTGRES_USER=bitcaster
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bitcaster
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "bitcaster"]
      start_period: 5s
      start_interval: 1s
      interval: 5s
      timeout: 4s
      retries: 5

  pgadmin:
      image: dpage/pgadmin4
      container_name: bitcaster_pgadmin4
      ports:
          - 3333:80
      environment:
          PGADMIN_DEFAULT_EMAIL: bitcaster
          PGADMIN_DEFAULT_PASSWORD: password
  redis:
    image: redis:7.2
    restart: always
    container_name: bitcaster_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      start_interval: 1s
      interval: 5s
      timeout: 4s
      retries: 5

volumes:
  postgres_data:
  static_storage:
