site_name: Bitcaster Documentation
site_url: https://example.com/

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.smartsymbols
  - pymdownx.smartsymbols
  - pymdownx.blocks.definition
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"

theme:
  name: "material"
  features:
    - content.tooltips

plugins:
  - search
  - ezlinks
  - mkdocstrings
  - mermaid2
  - awesome-pages
#
#nav:
#  - Home: index.md
#  - Glossary: glossary
#  - Guidelines: guidelines/index.md
#  - Todo: todo.md
#  - ClassDiagram: class-diagram.md
#  - Release Strategy: release-strategy.md
