[project]
name = "bitcaster"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "sax", email = "s.apostolico@gmail.com"},
]
dependencies = [
    "django>=5.0.3",
    "djangorestframework>=3.15.0",
    "django-admin-extra-buttons>=1.5.7",
    "django-adminactions>=2.3.0",
    "django-adminfilters>=2.4.3",
    "django-environ>=0.11.2",
    "django-constance>=3.1.0",
    "django-treebeard>=4.7.1",
    "psycopg2-binary>=2.9.9",
    "responses>=0.25.0",
    "requests>=2.31.0",
    "django-flags>=5.0.13",
    "sentry-sdk>=1.43.0",
    "celery>=5.3.6",
    "django-celery-beat>=2.6.0",
    "django-bitfield>=2.2.0",
    "django-debug-toolbar>=4.3.0",
    "qrcode>=7.4.2",
    "social-auth-app-django>=5.4.0",
    "social-auth-core>=4.5.3",
    "twilio>=9.0.2",
    "django-url-filter>=0.3.15",
    "phonenumbers>=8.13.32",
    "django-timezone-field>=6.1.0",
    "django-regex>=0.5.0",
    "htmlmin>=0.1.12",
    "premailer>=3.10.0",
    "python-gitlab>=4.4.0",
    "pygments>=2.17.2",
    "py-vapid>=1.9.0",
    "pillow>=10.2.0",
    "django-strategy-field>=3.1.0",
    "user-agents>=2.2.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "OS4D"}


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.1.1",
    "factory-boy>=3.3.0",
    "django-webtest>=1.9.11",
    "selenium>=4.18.1",
    "mypy>=1.9.0",
    "flake8>=7.0.0",
    "isort>=5.13.2",
    "black>=24.3.0",
    "django-csp>=3.8",
    "freezegun>=1.4.0",
    "pytest-coverage>=0.0",
    "pytest-django>=4.8.0",
    "pytest-selenium>=4.1.0",
    "mkdocs>=1.5.3",
    "mkdocstrings[python]>=0.24.1",
    "mkdocs-material>=9.5.15",
    "mkdocs-mermaid2-plugin>=1.1.1",
    "pygments>=2.17.2",
    "pymdown-extensions>=10.7.1"
    "pdbpp>=0.10.3",
    "django-stubs>=4.2.7",
    "django-stubs-ext>=4.2.7",
    "pytest-celery>=0.0.0",
    "pyupgrade>=3.15.1",
    "types-freezegun>=1.1.10",
    "types-python-dateutil>=2.9.0.20240316",
    "types-redis>=4.6.0.20240311",
    "types-requests>=2.31.0.20240311",
]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | snapshots
)/
'''

