[pytest]
norecursedirs = data .tox _plugin_template .idea  node_modules ~*
django_find_project = false
junit_family=legacy
pythonpath=src
testpaths=tests
tmp_path_retention_policy=all
tmp_path_retention_count=0
addopts =
        --reuse-db
        --tb=short
        --capture=sys
        --cov src
        --cov-config=tests/.coveragerc
        --cov-report html
        --cov-report xml:coverage.xml
timeout = 300
timeout_method = thread


markers =
    selenium
    api
    admin
    skip_models
    skip_buttons
    select_buttons
    smoke
    dispatcher
    wizard


python_files=test_*.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::django.utils.deprecation.RemovedInDjango61Warning
    ignore::coverage.exceptions.CoverageWarning
    ignore::UserWarning
