[tox]
envlist = d{21}-py{36}, lint

[testenv]
deps =
    pipenv


passenv =
    CI
    CIRCLE_*
    CIRCLECI
    DATABASE_URL
    PYTHONDONTWRITEBYTECODE
    PYTHONPATH
    PWD
    USER

setenv =
    PYTHONDONTWRITEBYTECODE=true
    PYTHONPATH={toxinidir}/src


commands =
    pipenv install -d --deploy --ignore-pipfile
    pipenv run py.test tests \
            --create-db \
            --cov-report=term \
            --cov-report=html \
            --cov-config=tests/.coveragerc \
            --cov=bitcaster

[testenv:lint]
commands =
    pipenv run pre-commit run --all-files --hook-stage push
