[tox]
envlist = d{22}-py{36,37,py}

[testenv]
deps =
    pipenv


passenv =
    CFLAGS
    CI
    CIRCLE_*
    CIRCLECI
    CLANG
    DATABASE_URL
    PYTHONDONTWRITEBYTECODE
    PYTHONPATH
    PWD
    USER
    BITCASTER_*

setenv =
    PYTHONDONTWRITEBYTECODE=true
    PYTHONPATH={toxinidir}/src
    BITCASTER_SECRET_KEY=very-super-secret-key
    BITCASTER_FERNET_KEYS=very-super-secret-key

commands =
    pipenv run {posargs:pytest tests \
            --create-db \
            --cov-report=term \
            --cov-report=html \
            --cov-config=tests/.coveragerc \
            --cov=bitcaster}

[testenv:lint]
commands =
    pip install pre-commit isort
    pre-commit run --all-files --hook-stage push
