[tox]
requires =
    tox>=4.2
    tox-uv>=1.25
env_list =
    lint
    dj52
    docs
    pkg_meta

[testenv]
description = run unit tests
pass_env =
    CACHE_URL
    CELERY_BROKER_URL
    DATABASE_URL
set_env =
    PYTHONDONTWRITEBYTECODE = 1
    SECRET_KEY = super-secret-key-just-for-testing
commands =
    {posargs:pytest --create-db --migrations -v --maxfail 5 tests}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
description = build mkdocs documentation
skip_install = false
deps =
set_env =
    SECRET_KEY = super-secret-key-just-for-testing
commands =
    mkdocs build {posargs:}
dependency_groups = docs

[testenv:pkg_meta]
runner = uv-venv-runner
description = check python package
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build -q --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --ignore W002,W004,W009,W004 {env_tmp_dir}
