# Generated by Django 5.0.4 on 2024-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AZUREAD_OAUTH2", "Azure"),
                            ("AZUREAD_TENANT_OAUTH2", "Azure Tenant"),
                            ("FACEBOOK", "Facebook"),
                            ("GITHUB", "Github"),
                            ("GITHUB_ENTERPRISE", "Gitehub Enterprise"),
                            ("GITHUB_ORG", "Github Organization"),
                            ("GITHUB_TEAM", "Github Team"),
                            ("GOOGLE_OAUTH2", "Google"),
                            ("LINKEDIN_OAUTH2", "Linkedin"),
                            ("TWITTER", "Twitter"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
