# Generated by Django 5.2.11 on 2026-03-13 10:26

from django.db import migrations, models

LABEL_MAP = {
    "facebook": "Facebook",
    "github": "Github",
    "gitlab": "Gitlab",
    "google": "Google",
    "linkedin_oauth2": "Linkedin",
    "microsoft": "Microsoft",
    "twitter": "Twitter",
    "wso2": "Wso2",
    "openid_connect": "Keycloak",
}


def forward(apps, schema_editor):
    SocialProvider = apps.get_model("social", "SocialProvider")
    for obj in SocialProvider.objects.all():
        obj.label = LABEL_MAP.get(obj.provider, obj.provider)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialprovider",
            name="label",
            field=models.CharField(help_text="Label", max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(forward),
    ]
