# Generated by Django 5.2.11 on 2026-03-13 10:26

from django.db import migrations, models


def forward(apps, schema_editor):
    from bitcaster.social.models import Provider

    SocialProvider = apps.get_model("social", "SocialProvider")
    for obj in SocialProvider.objects.all():
        obj.label = Provider[obj.provider.replace("-", "_")].label
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialprovider",
            name="label",
            field=models.CharField(help_text="Label", max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(forward),
    ]
