# Generated by Django 5.0.4 on 2024-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprovider",
            name="provider",
            field=models.CharField(
                choices=[
                    ("AZUREAD_OAUTH2", "Azure"),
                    ("AZUREAD_TENANT_OAUTH2", "Azure Tenant"),
                    ("FACEBOOK", "Facebook"),
                    ("GITHUB", "Github"),
                    ("GITHUB_ENTERPRISE", "Github Enterprise"),
                    ("GITHUB_ORG", "Github Organization"),
                    ("GITLAB", "Gitlab"),
                    ("GITHUB_TEAM", "Github Team"),
                    ("GOOGLE_OAUTH2", "Google"),
                    ("LINKEDIN_OAUTH2", "Linkedin"),
                    ("TWITTER", "Twitter"),
                    ("OAUTH2", "oauth2"),
                ],
                help_text="Social Login provider",
                max_length=30,
                unique=True,
            ),
        ),
    ]
