# Generated by Django 5.2.11 on 2026-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_socialprovider_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprovider",
            name="label",
            field=models.CharField(help_text="Label", max_length=50, unique=True),
        ),
    ]
