# Generated by Django 5.2.13 on 2026-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_alter_socialprovider_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprovider",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration as per Python Social Auth",
                verbose_name="Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="socialprovider",
            name="enabled",
            field=models.BooleanField(default=True, help_text="Provider status", verbose_name="Enabled"),
        ),
        migrations.AlterField(
            model_name="socialprovider",
            name="label",
            field=models.CharField(help_text="Label", max_length=50, unique=True, verbose_name="label"),
        ),
        migrations.AlterField(
            model_name="socialprovider",
            name="provider",
            field=models.CharField(
                choices=[
                    ("AZUREAD_OAUTH2", "Azure"),
                    ("AZUREAD_TENANT_OAUTH2", "Azure Tenant"),
                    ("FACEBOOK", "Facebook"),
                    ("GITHUB", "Github"),
                    ("GITHUB_ENTERPRISE", "Github Enterprise"),
                    ("GITHUB_ORG", "Github Organization"),
                    ("GITLAB", "Gitlab"),
                    ("GITHUB_TEAM", "Github Team"),
                    ("GOOGLE_OAUTH2", "Google"),
                    ("LINKEDIN_OAUTH2", "Linkedin"),
                    ("TWITTER", "Twitter"),
                    ("OAUTH2", "oauth2"),
                    ("WSO2", "Wso2"),
                    ("KEYCLOAK", "Keycloak"),
                ],
                help_text="Social Login provider",
                max_length=30,
                unique=True,
                verbose_name="provider",
            ),
        ),
    ]
