# Generated by Django 5.2.13 on 2026-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_migrate_social_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialprovider",
            name="client_id",
            field=models.CharField(
                blank=True, help_text="App ID or Client ID", max_length=191, verbose_name="Client ID"
            ),
        ),
        migrations.AddField(
            model_name="socialprovider",
            name="key",
            field=models.CharField(
                blank=True, help_text="Optional extra key (if required by provider)", max_length=191, verbose_name="Key"
            ),
        ),
        migrations.AddField(
            model_name="socialprovider",
            name="secret",
            field=models.CharField(
                blank=True, help_text="API Secret or Client Secret", max_length=191, verbose_name="Secret"
            ),
        ),
        migrations.AlterField(
            model_name="socialprovider",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra provider-specific settings",
                verbose_name="Extra Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="socialprovider",
            name="provider",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("github", "Github"),
                    ("gitlab", "Gitlab"),
                    ("google", "Google"),
                    ("linkedin_oauth2", "Linkedin"),
                    ("microsoft", "Microsoft"),
                    ("twitter", "Twitter"),
                    ("wso2", "Wso2"),
                    ("openid_connect", "Keycloak"),
                ],
                help_text="Social Login provider",
                max_length=30,
                unique=True,
                verbose_name="provider",
            ),
        ),
    ]
