# Generated by Django 5.2.13 on 2026-04-24 18:18

from django.db import migrations, models

import bitcaster.social.models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_populate_credential_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprovider",
            name="provider",
            field=models.CharField(
                choices=bitcaster.social.models.get_provider_choices,
                help_text="Social Login provider",
                max_length=30,
                unique=True,
                verbose_name="provider",
            ),
        ),
    ]
