# Generated by Django 5.2.14 on 2026-05-15 20:07

from django.db import migrations, models

import bitcaster.social.models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0009_cleanup_legacy_social_auth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprovider",
            name="provider",
            field=models.CharField(
                choices=bitcaster.social.models.get_provider_choices,
                help_text="Social Login provider",
                max_length=30,
                verbose_name="provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialprovider",
            constraint=models.UniqueConstraint(fields=("client_id", "provider"), name="unique_client_provider"),
        ),
    ]
