[pytest]
norecursedirs = data .tox _plugin_template
django_find_project = false
addopts =
        -p no:xdist
        -p no:pep8
        --doctest-modules
        --reuse-db
        --tb=short
        --capture=no
        --cov-report=html
        --cov-config=tests/.coveragerc
        --cov=mercury_{{cookiecutter.name}}


python_files=test_*.py
pep8ignore = * ALL
