[tox]
envlist =
    py{27,36}-d{18,19,110,111}

[pytest]
python_paths=./tests/demo/
DJANGO_SETTINGS_MODULE=demoproject.settings
python_files=tests/test_*.py
doctest_optionflags=ELLIPSIS ALLOW_UNICODE ALLOW_UNICODE
norecursedirs = data .tox geo
addopts =
        --reuse-db
        --doctest-modules
        --tb=short
        --capture=no
        --cov-report=html
        --cov-config=tests/.coveragerc
        --cov geo
        --echo-version django
        --echo-attr django.conf.settings.DATABASES.default.ENGINE
pep8ignore = * ALL

deps=
    d17: django>=1.7,<1.8
    d18: django>=1.8,<1.9
    d19: django>=1.9,<1.10
    d110: django>=1.10,<1.11
    d111: django>=1.11,<1.12
    d20: django>=2.0dev,<2.1
    dtrunk: git+git://github.com/django/django.git#egg=django

[testenv]
changedir={toxinidir}

commands =
    {posargs:py.test tests/ \
            --cov-report=html \
            --cov-config=tests/.coveragerc \
            --cov geo --create-db}
