# ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Calculate Release Hash'
description: 'Calculate deps and os hash'
inputs:
  files:
    description: 'Files to use to calculate the hash'
    required: true
    default: "pdm.lock docker/bin/* docker/conf/* docker/Dockerfile"
outputs:
  checksum: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.calc.outputs.checksum }}

runs:
  using: 'composite'
  steps:
    - id: calc
      shell: bash
      run: |
        set -x
        LOCK_SHA=$(sha1sum ${{ inputs.files }} | sha1sum | awk '{print $1}' | cut -c 1-8)
        echo "checksum=$LOCK_SHA" >> "$GITHUB_OUTPUT"
