version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
#      - image: python:3.6.8-alpine3.8
      - image: bitcaster/bitcaster-0.4:base-dev
        environment:
          PGHOST: 127.0.0.1
          DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5432/bitcaster"
          RELEASE_MATCH: "release/*"
      - image: circleci/postgres:9.6-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          PGUSER: postgres
          POSTGRES_DB: bitcaster
          POSTGRES_PASSWORD: postgres
      - image: redis:alpine
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}

      - checkout
      - restore_cache:
          keys:
            - deps-v2-{{ checksum "Pipfile.lock" }}

      - run:
          name: install packeges
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            export PYTHONHASHSEED=${RANDOM}
            pip install pipenv
      - run:
          name: run tests
          environment:
              BITCASTER_CELERY_BROKER_URL: redis://127.0.0.1:6379/2
              BITCASTER_DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/bitcaster
              BITCASTER_DEBUG: 1
              BITCASTER_DEBUG_TOOLBAR: True
              BITCASTER_LOG_LEVEL: DEBUG
              BITCASTER_FAKE_OTP:
              BITCASTER_ON_PREMISE: True
              BITCASTER_PLUGINS_AUTOLOAD: False
              BITCASTER_REDIS_CACHE_URL: redis://127.0.0.1:6379/0?key_prefix=bitcaster
              BITCASTER_REDIS_LOCK_URL: redis://127.0.0.1:6379/1?key_prefix=bitcaster-lock
              BITCASTER_REDIS_TSDB_URL: redis://127.0.0.1:6379/3
              BITCASTER_SECRET_KEY: "c+#b: 7f7!xxx^8wo!kx9wzu%h_lyabc-gbt0)+%3tz73!6!q!5"
              BITCASTER_FERNET_KEYS: "c+#b: 7f7!xxx^8wo!kx9wzu%h_lyabc-gbt0)+%3tz73!6!q!5,"
              BITCASTER_MEDIA_ROOT: /tmp/media
              BITCASTER_STATIC_ROOT: /tmp/static
          command: |
            pipenv run pytest tests \
                        --maxfail=10 \
                        --create-db \
                        --cov-report=term \
                        --cov-report=html \
                        --cov-config=tests/.coveragerc \
                        --cov=bitcaster

      - store_artifacts:
          path: ~build/coverage
          destination: coverage

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - save_cache:
          key: deps-v2-{{ checksum "Pipfile.lock" }}
          paths:
            - "/usr/local/lib/python3.6"
            - "~/.cache/pip"

      - deploy:
          name: tag and release if release candidate
          command: |
              if [[ $CIRCLE_BRANCH == $RELEASE_MATCH ]]; then
                curl --user ${CIRCLE_TOKEN}: \
                  --data build_parameters[CIRCLE_JOB]=tag \
                  --data revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              else
                echo "Skipped as '$CIRCLE_BRANCH' does not match '$RELEASE_MATCH' branch"
              fi
  tag:
    docker:
      - image: circleci/python:3.6
        environment:
          API_URL: https://api.github.com/repos/bitcaster-io/bitcaster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "36:e1:ae:c3:f2:0f:27:67:85:44:78:5d:ec:2f:b2:0d"
      - run:
          name: package and release
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            export TAG=${TAG:=${CIRCLE_BRANCH#*/}}
            git status
            git reset --hard

            git config user.email "ci@bitcaster.org"
            git config user.name "CI"

            git checkout master
            git merge --no-ff release/$TAG -m "merge release/$TAG"
            git tag -a -m "v$TAG" $TAG
            git checkout develop
            git merge --no-ff release/$TAG -m "merge release/$TAG"
            git push --verbose --tags
            git push origin --verbose --delete release/$TAG
      - run:
          name: release
          command: |
              curl --user ${CIRCLE_TOKEN}: \
                  --data build_parameters[CIRCLE_JOB]=release \
                  --data revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH

  release:
    docker:
      - image: circleci/python:3.6
        environment:
          API_URL: https://api.github.com/repos/bitcaster-io/bitcaster
    steps:
      - run:
          name: github release
          command: |
            export TAG=${TAG:=${CIRCLE_BRANCH#*/}}
            export TODAY=`date '+%d %B %Y at %H:%M'`
            function is_pre()
            {
                [[ "$(echo "$TAG" | sed 's/[0-9.]//g')" == "" ]] && echo false || echo true
            }
            function data() {
            cat <<EOF
            { "tag_name": "$TAG",
              "name": "v$TAG",
              "body": "version $TAG - Built on $TODAY",
              "draft": false,
              "prerelease": $(is_pre)
            }
            EOF
            }
            data=$(data)
            curl -X POST \
              --fail \
              --trace \
              -H "Accept: application/json" \
              -H "Content-Type:application/json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              ${API_URL}/releases \
              -d "$data"
      - run:
          name: notify slack
          command: |
            WEBHOOK_URL=https://hooks.slack.com/services/${SLACK_WEBHOOK}
            CHANNEL=ci
            escapedText=$(echo "Released new version $TAG" | sed 's/"/\"/g' | sed "s/'/\'/g" )
            json="{\"channel\": \"$CHANNEL\", \"username\":\"CircleCI\", \"attachments\":[{\"color\":\"good\" , \"text\": \"$escapedText\"}]}"

            echo $json | jq .

            curl -s -d "payload=$json" "$WEBHOOK_URL"
