# Generated by Django 2.0.2 on 2018-02-15 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, db_index=True, help_text='ISO 3166-2 code', max_length=10, null=True, verbose_name='Code')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Administrative Area',
                'verbose_name_plural': 'Administrative Areas',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Administrative Area Type',
                'verbose_name_plural': 'Administrative Area Types',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha 2', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('iso_code3', models.CharField(db_index=True, help_text='ISO 3166-1 alpha 3', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('iso_num', models.CharField(help_text='ISO 3166-1 numeric', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('\\d\\d\\d')])),
                ('undp', models.CharField(blank=True, help_text='UNDP code', max_length=3, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nato3', models.CharField(blank=True, help_text='NATO3 code', max_length=3, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('fips', models.CharField(blank=True, help_text='fips code', max_length=255, null=True)),
                ('itu', models.CharField(blank=True, help_text='ITU code', max_length=255, null=True)),
                ('icao', models.CharField(blank=True, help_text='ICAO code', max_length=255, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('fullname', models.CharField(db_index=True, max_length=100)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antartica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2)),
                ('tld', models.CharField(blank=True, help_text='Internet tld', max_length=5, null=True)),
                ('phone_prefix', models.CharField(blank=True, help_text='Phone prefix number', max_length=20, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, default=None, null=True)),
                ('expired', models.DateField(blank=True, default=None, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryNameTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('language_iso_code', models.CharField(db_index=True, help_text='Language iso code', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('translation', models.CharField(blank=True, help_text='Translation', max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country')),
            ],
            options={
                'verbose_name_plural': 'Country Name Translations',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(db_index=True, help_text='ISO 4217 code', max_length=5, unique=True)),
                ('numeric_code', models.CharField(help_text='ISO 4217 code', max_length=5, unique=True)),
                ('decimals', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['iso_code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_capital', models.BooleanField(default=False, help_text='True if is the capital of `country`')),
                ('is_administrative', models.BooleanField(default=False, help_text='True if is administrative for `area`')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('loccode', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UN LOCODE')),
                ('iata', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='IATA code (if exists)')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('acc', models.IntegerField(blank=True, choices=[(0, 'None'), (10, 'Country'), (20, 'Exact')], default=0, help_text='Define the level of accuracy of lat/lng infos', null=True)),
                ('geoname_id', models.IntegerField(blank=True, null=True, verbose_name='Geoname')),
                ('status', models.CharField(blank=True, choices=[('AA', 'Approved by competent national government agency'), ('AC', 'Approved by Customs Authority'), ('AF', 'Approved by national facilitation body'), ('AI', 'Code adopted by international organisation (IATA or ECLAC)'), ('RL', 'Recognised location - Existence and representation of location name confirmed by check against nominated gazetteer or other reference work'), ('RN', 'Request from credible national sources for locations in their own country'), ('RQ', 'Request under consideration'), ('RR', 'Request rejected'), ('QQ', 'Original entry not verified since date indicated'), ('XX', 'Entry that will be removed from the next issue of UN/LOCODE')], max_length=2, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='geo.AdministrativeArea')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='geo.Country')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('country', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
            },
        ),
        migrations.CreateModel(
            name='UNRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'UN Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='geo.LocationType'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.UNRegion'),
        ),
        migrations.AddField(
            model_name='administrativeareatype',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='geo.Country'),
        ),
        migrations.AddField(
            model_name='administrativeareatype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geo.AdministrativeAreaType'),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='geo.Country'),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='geo.AdministrativeArea'),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='geo.AdministrativeAreaType'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('loccode', 'country'), ('area', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='administrativeareatype',
            unique_together={('country', 'name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='administrativearea',
            unique_together={('name', 'country', 'type', 'parent')},
        ),
    ]
