# Generated by Django 2.0.2 on 2018-02-15 13:38
import pycountry
from django.db import migrations, IntegrityError


def truncate(model):
    from django.db import connection
    cursor = connection.cursor()
    sql = "TRUNCATE TABLE {} CASCADE".format(model._meta.db_table)
    cursor.execute(sql)


def load(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')
    Currency = apps.get_model('geo', 'Currency')
    AdministrativeArea = apps.get_model('geo', 'AdministrativeArea')
    AdministrativeAreaType = apps.get_model('geo', 'AdministrativeAreaType')
    for c in pycountry.countries:
        try:
            lang = pycountry.languages.get(alpha_2=c.alpha_2.lower())
        except KeyError:
            lang = None
        Country.objects.get_or_create(
            iso_code=c.alpha_2,
            defaults=dict(name=c.name,
                          fullname=getattr(c, 'official_name', c.name),
                          iso_code3=c.alpha_3,
                          iso_num=c.numeric)
        )

    for c in pycountry.currencies:
        Currency.objects.get_or_create(
            iso_code=c.alpha_3,
            defaults=dict(name=c.name, numeric_code=c.numeric)
        )
    for a in pycountry.subdivisions:
        if a.parent_code:
            aa = pycountry.subdivisions.get(code=a.parent_code)
            parent = AdministrativeAreaType.objects.filter(country__iso_code=aa.country_code,
                                                           name=aa.type).first()
        else:
            parent = None

            AdministrativeAreaType.objects.get_or_create(
                name=a.type,
                country=Country.objects.get(iso_code=a.country_code),
                parent=parent,
                lft=0,
                rght=0,
                tree_id=0,
                level=0,
            )

            AdministrativeArea.objects.get_or_create(
                name=a.name,
                code=a.code,
                lft=0,
                rght=0,
                tree_id=0,
                level=0,
                type=AdministrativeAreaType.objects.filter(country__iso_code=a.country_code,
                                                           name=a.type,
                                                           ).first(),
                country=Country.objects.get(iso_code=a.country_code),
                parent=AdministrativeArea.objects.filter(code=a.parent_code).first()
            )


def unload(apps, schema_editor):
    # Country = apps.get_model('geo', 'Country')
    truncate(apps.get_model('geo', 'Country'))
    truncate(apps.get_model('geo', 'Currency'))
    truncate(apps.get_model('geo', 'AdministrativeArea'))
    truncate(apps.get_model('geo', 'AdministrativeAreaType'))


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load, unload),

    ]
