[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
umask = 002
working_dir=$(CIRCUS.ENV.PWD)
;httpd = true
;httpd_host = 0.0.0.0
;httpd_port = 15000
debug = true
stdout_stream.class=StdoutStream
stderr_stream.class=StdoutStream

[env:*]
PATH = $PATH
BITCASTER_CELERY_BROKER_URL=$BITCASTER_CELERY_BROKER_URL
BITCASTER_CELERY_TASK_ALWAYS_EAGER=$BITCASTER_CELERY_TASK_ALWAYS_EAGER
BITCASTER_CONF=$BITCASTER_CONF
BITCASTER_DATABASE_URL=$BITCASTER_DATABASE_URL
BITCASTER_DEBUG=$BITCASTER_DEBUG
BITCASTER_FERNET_KEYS=$BITCASTER_FERNET_KEYS
BITCASTER_LOG_LEVEL=$BITCASTER_LOG_LEVEL
BITCASTER_MEDIA_ROOT=$BITCASTER_MEDIA_ROOT
BITCASTER_REDIS_CACHE_URL=$BITCASTER_REDIS_CACHE_URL
BITCASTER_REDIS_LOCK_URL=$BITCASTER_REDIS_LOCK_URL
BITCASTER_REDIS_TSDB_URL=$BITCASTER_REDIS_TSDB_URL
BITCASTER_SECRET_KEY=$BITCASTER_SECRET_KEY
BITCASTER_SENTRY_DSN=$BITCASTER_SENTRY_DSN
BITCASTER_SENTRY_ENABLED=$BITCASTER_SENTRY_ENABLED
BITCASTER_STATIC_ROOT=$BITCASTER_STATIC_ROOT

[env:bitcaster]
GUNICORN_CMD_ARGS=$GUNICORN_CMD_ARGS
HOME=$HOME

[watcher:bitcaster]
cmd=gunicorn
args=-b 0.0.0.0:8000 bitcaster.config.wsgi --access-logfile - --error-logfile - --log-level debug
user=bitcaster
use_sockets = True

[watcher:worker]
cmd=celery
args=worker -A bitcaster --loglevel=DEBUG --concurrency=4 --pidfile celery.pid
user=bitcaster


[watcher:beat]
cmd=celery
args=beat -A bitcaster --loglevel=DEBUG --pidfile celerybeat.pid
user=bitcaster
