FROM saxix/pypg:1.0-alpine
USER root

ENV PIPSI_HOME /usr/local/pipsi/environments
ENV PIPSI_BIN_DIR /usr/local/bin

RUN apk add --no-cache redis
EXPOSE 6379

RUN apk upgrade && apk update && \
    apk add --no-cache --virtual .build-deps \
        curl \
        gcc \
        python3-dev \
        postgresql-dev \
        postgresql-libs \
        musl-dev \
        #  fatal error: libxml/xmlversion.h: No such file or directory
        libxslt-dev \
        libffi-dev \
#        openssl-dev \
#        django-sysinfo / psutil
        linux-headers

RUN apk add --no-cache --virtual .runtime-deps \
        # Pillow dependencies
        freetype-dev \
        lcms2-dev \
        openjpeg-dev \
        tiff-dev \
        tk-dev \
        tcl-dev \
        harfbuzz-dev \
        fribidi-dev \
        jpeg-dev \
        zlib-dev


RUN mkdir -p /code /root/.local/bin

RUN pip install -U pip \
    && curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python \
    && pip install virtualenv \
    && /usr/local/bin/pipsi install pipenv


WORKDIR /code
COPY . /code
ENV POSTGRES_DB bitcaster
ENV BITCASTER_DATABASE_URL psql://postgres:@127.0.0.1:5432/${POSTGRES_DB}

RUN pipenv install -v --system --deploy \
    && mkdir -p /var/bitcaster/ -m 770 \
    && mkdir -p /root/.bitcaster/ -m 770 \
    && pip install . \
    && /code/plugins/install-plugins.sh /code/plugins/



RUN apk del .build-deps\
    && rm -fr /code \
    && rm -fr /root/.cache

ADD docker/marvel.txt /
ADD docker/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["bitcaster"]
