version: '3'

services:
  web:
#    build: .
    image: bitcaster:beta
    command: bash
    tty: true
    volumes:
#      - $PWD:/usr/src/bitcaster
      - /data/storage/bitcaster/etc/:/etc/bitcaster
      - /data/storage/bitcaster/var/bitcaster/:/var/bitcaster
    ports:
      - "${DOCKER_WEB_PORT}:8000"
    depends_on:
      - db
      - redis
      - sentry

  workers:
    image: bitcaster:beta
    command: bitcaster start workers -l debug
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - sentry

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - ${DOCKER_REDIS_DATA}:/data

  db:
    image: mdillon/postgis
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
    volumes:
      - ${DOCKER_POSTGRES_DATA}:/var/lib/postgresql/data
    restart: unless-stopped

  sentry:
    image: saxix/sentry-localdev
    environment:
      - SENTRY_SECRET_KEY=abc
      - SENTRY_REDIS_HOST=redis
      - SENTRY_DB_NAME=sentry
      - SENTRY_POSTGRES_HOST=db
      - SENTRY_ADMIN_USERNAME=sax
      - SENTRY_ADMIN_PASSWORD=123
      - C_FORCE_ROOT=1 # never in production
    links:
      - "redis:redis"
      - "db:db"
    ports:
      - ${DOCKER_SENTRY_PORT}:9000
    volumes:
      - ${DOCKER_SENTRY_DATA}:/conf
    restart: unless-stopped
    depends_on:
      - db
      - redis
