FROM saxix/pypg:1.0-slim as builder
USER root

ENV PIPSI_HOME /usr/local/pipsi/environments
ENV PIPSI_BIN_DIR /usr/local/bin
    RUN apt-get update && apt-get install -y --no-install-recommends \
        ntp \
        vim \
        curl \
        gcc \
        linux-libc-dev \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /code /root/.local/bin

RUN pip install -U pip \
    && curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python \
    && pip install virtualenv \
    && pipsi install pipenv

WORKDIR /code
COPY . /code
RUN pipenv install -v --system --deploy \
    && pip install . \
    && rm -fr /code
#FROM saxix/pypg:1.0-slim

ADD docker/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["bitcaster"]
