[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket

[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[inet_http_server]               ; inet (TCP) server disabled by default
port=*:15000                     ; (ip_address:port specifier, *:port for all iface)
username=%(ENV_SUPERVISOR_USER)s ; (default is no username (open server))
password=%(ENV_SUPERVISOR_PWD)s  ; (default is no password (open server))


[supervisord]
childlogdir=log ; where child log files will live
directory=/var/bitcaster
environment=DJANGO_SETTINGS_MODULE="bitcaster.config.settings"
logfile=log/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_backups=1
logfile_maxbytes=512Kb
loglevel=error                ; (log level;default info; others: debug,warn,trace)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)
nodaemon=false               ; (start in foreground if true;default false)
pidfile=run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)

[program:bitcaster]
directory=/var/bitcaster
command=gunicorn -b 0.0.0.0:8000 bitcaster.config.wsgi
autostart=true
autorestart=true
stderr_logfile=log/err.log
stdout_logfile=out.log


[program:workers]
command=celery worker -A bitcaster --loglevel=DEBUG --concurrency=4 --purge --pidfile run/celery.pid
autostart=true
autorestart=false
numprocs=1
redirect_stderr=true
logfile_maxbytes=512Kb
priority=700
startretries=3
startsecs=10
stopwaitsecs=600


[program:beat]
command=celery beat -A bitcaster --loglevel=DEBUG --pidfile run/celerybeat.pid
autostart=true
autorestart=false
numprocs=1
redirect_stderr=true
logfile_maxbytes=512Kb
priority=700
startretries=3
startsecs=10
stopwaitsecs=600
