[uwsgi]
;socket = /tmp/uwsgi.sock
;chown-socket = nginx:nginx
;chmod-socket = 664
;cheaper = 2
;processes = 16
;wsgi-file=/app/main.py

chdir = /data
master = true
processes = 4
socket = /var/run/uwsgi.sock
env = DJANGO_SETTINGS_MODULE=mercury.settings.default
module = mercury.config.wsgi
no-orphans = true

# the fix
lazy-apps = true
