# Generated by Django 5.0.4 on 2024-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locked",
            field=models.BooleanField(default=False, help_text="Security lock of project"),
        ),
    ]
