# Generated by Django 2.2 on 2019-04-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
