# Generated by Django 2.1.7 on 2019-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmetadata',
            options={'ordering': ('fqn',)},
        ),
        migrations.AlterModelOptions(
            name='dispatchermetadata',
            options={'ordering': ('fqn',)},
        ),
        migrations.AlterField(
            model_name='applicationtriggerkey',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
