# Generated by Django 5.2.9 on 2025-12-23 20:10

import concurrency.fields
import django.contrib.postgres.fields
import django.core.files.storage
import django.db.models.deletion
import smart_selects.db_fields
import strategy_field.fields
from django.conf import settings
from django.db import migrations, models

import bitcaster.models.key
import bitcaster.models.log
import bitcaster.models.media
import bitcaster.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bitcaster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[],
            options={
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", bitcaster.models.log.LogEntryManager()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bitcaster.user",),
            managers=[
                ("objects", bitcaster.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(help_text="Label or mnemonic name for this address", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GENERIC", "Generic address"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("account", "Account"),
                        ],
                        default="GENERIC",
                        help_text="Type of address",
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(help_text="Specific address value.", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("user", "name"), ("user", "value")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="If checked any notification is ignored and not forwarded"
                    ),
                ),
                ("paused", models.BooleanField(default=False, help_text="If checked any notification paused")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True, help_text="Whether the application should be active")),
                (
                    "auto_crete_event",
                    models.BooleanField(
                        default=False, help_text="If true unknown events will be automatically created"
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, default="", help_text="default from address for emails", max_length=254
                    ),
                ),
                (
                    "subject_prefix",
                    models.CharField(
                        default="[Bitcaster] ",
                        help_text="Default prefix for messages supporting subject",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="If checked any notification is ignored and not forwarded"
                    ),
                ),
                ("paused", models.BooleanField(default=False, help_text="If checked any notification paused")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("dispatcher", strategy_field.fields.StrategyField(default="test")),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("PLAINTEXT", "Plaintext"),
                            ("SLACK", "Slack"),
                            ("SMS", "Sms"),
                            ("EMAIL", "Email"),
                            ("WEBPUSH", "Webpush"),
                        ],
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="organization",
                        chained_model_field="organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bitcaster.channel",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("validated", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="bitcaster.address"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="bitcaster.channel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "unique_together": {("address", "channel")},
            },
        ),
        migrations.CreateModel(
            name="DistributionList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(db_collation="case_insensitive", max_length=255)),
                ("recipients", models.ManyToManyField(blank=True, to="bitcaster.assignment")),
            ],
            options={
                "verbose_name": "Distribution List",
                "verbose_name_plural": "Distribution Lists",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="If checked any notification is ignored and not forwarded"
                    ),
                ),
                ("paused", models.BooleanField(default=False, help_text="If checked any notification paused")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "newsletter",
                    models.BooleanField(default=False, help_text="Do not customise notifications per single user"),
                ),
                (
                    "occurrence_retention",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days (from last update) after which related Occurrences can be purged. "
                        "If not specified, system default will be used.",
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="bitcaster.application"
                    ),
                ),
                ("channels", models.ManyToManyField(blank=True, to="bitcaster.channel")),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("name", "application"), ("slug", "application")},
            },
        ),
        migrations.CreateModel(
            name="LogMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "CRITICAL"),
                            ("FATAL", "FATAL"),
                            ("ERROR", "ERROR"),
                            ("WARN", "WARN"),
                            ("WARNING", "WARNING"),
                            ("INFO", "INFO"),
                            ("DEBUG", "DEBUG"),
                            ("NOTSET", "NOTSET"),
                        ],
                        max_length=255,
                    ),
                ),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.application"),
                ),
            ],
            options={
                "verbose_name": "Log Message",
                "verbose_name_plural": "Log Messages",
            },
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("agent", strategy_field.fields.StrategyField()),
                ("active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict, editable=False)),
                ("data", models.JSONField(blank=True, default=dict, editable=False)),
                ("result", models.JSONField(blank=True, default=dict, editable=False)),
                ("async_result", models.CharField(blank=True, default="", editable=False, max_length=255)),
                ("schedule", models.CharField(blank=True, default="", max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="bitcaster.event"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "environments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20, null=True),
                        blank=True,
                        help_text="Allow notification only for these environments",
                        null=True,
                        size=None,
                    ),
                ),
                ("payload_filter", models.TextField(blank=True, null=True)),
                ("extra_context", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=False)),
                (
                    "external_filtering",
                    models.BooleanField(
                        default=False, help_text="Allow filtering recipients based on rules passed in the api call"
                    ),
                ),
                (
                    "dynamic",
                    models.BooleanField(
                        default=False,
                        help_text="Dynamic notification do not need DistributionList. "
                        "It filters users based on 'recipients_filter' rules",
                    ),
                ),
                ("recipients_filter", models.JSONField(blank=True, default=dict)),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="bitcaster.distributionlist",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="bitcaster.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when occurrence has been created."),
                ),
                ("context", models.JSONField(blank=True, default=dict, help_text="Context provided by the sender")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Options provided by the sender to route linked notifications",
                    ),
                ),
                ("correlation_id", models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ("recipients", models.IntegerField(default=0, help_text="Total number of reached recipients")),
                (
                    "newsletter",
                    models.BooleanField(default=False, help_text="Do not customise notifications per single user"),
                ),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Information about the processing (recipients, channels)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PROCESSED", "Processed"), ("FAILED", "Failed"), ("NEW", "New")],
                        default="NEW",
                        help_text="Status of the occurrence",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=5)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.event")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bitcaster.occurrence",
                    ),
                ),
            ],
            options={
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, default="", help_text="default from address for emails", max_length=254
                    ),
                ),
                (
                    "subject_prefix",
                    models.CharField(
                        default="[Bitcaster] ",
                        help_text="Default prefix for messages supporting subject",
                        max_length=50,
                        verbose_name="Subject Prefix",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.organization",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="If checked any notification is ignored and not forwarded"
                    ),
                ),
                ("paused", models.BooleanField(default=False, help_text="If checked any notification paused")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, default="", help_text="default from address for emails", max_length=254
                    ),
                ),
                (
                    "subject_prefix",
                    models.CharField(
                        default="[Bitcaster] ",
                        help_text="Default prefix for messages supporting subject",
                        max_length=50,
                        verbose_name="Subject Prefix",
                    ),
                ),
                (
                    "environments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20, null=True),
                        blank=True,
                        help_text="Environments available for project",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="bitcaster.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "subject",
                    models.TextField(
                        blank=True, help_text="The subject of the message", null=True, verbose_name="subject"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="The content of the message", verbose_name="content"),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True, help_text="The HTML formatted content of the message", verbose_name="HTML Content"
                    ),
                ),
                (
                    "application",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="project",
                        chained_model_field="project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.application",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Channel for which  the message is valid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bitcaster.channel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Event to which this message belongs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bitcaster.event",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="Notification to which this message belongs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bitcaster.notification",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.organization",
                    ),
                ),
                (
                    "project",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="organization",
                        chained_model_field="organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "image",
                    bitcaster.models.media.ImageFieldWithExtra(
                        height_field="height",
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        width_field="width",
                    ),
                ),
                ("size", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("width", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("height", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "application",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="project",
                        chained_model_field="project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.application",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.organization",
                    ),
                ),
                (
                    "project",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="organization",
                        chained_model_field="organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distributionlist",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.project"),
        ),
        migrations.AddField(
            model_name="channel",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.project",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="bitcaster.project"
            ),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(db_collation="case_insensitive", max_length=255, verbose_name="Name")),
                (
                    "key",
                    models.CharField(
                        default=bitcaster.models.key.make_token, max_length=255, unique=True, verbose_name="Token"
                    ),
                ),
                (
                    "grants",
                    bitcaster.models.key.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("FULL_ACCESS", "Full Access"),
                                ("SYSTEM_PING", "Ping"),
                                ("USER_READ", "User Read"),
                                ("USER_WRITE", "User Write"),
                                ("ORG_READ", "Organization Read"),
                                ("APPLICATION_ADMIN", "Application Admin"),
                                ("EVENT_LIST", "Event list"),
                                ("EVENT_TRIGGER", "Event Trigger"),
                                ("EVENT_AUTO_CREATE", "Event Auto-Create"),
                                ("DISTRIBUTION_LIST", "Distribution list"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "environments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20, null=True),
                        blank=True,
                        help_text="Limit validity to these environments. "
                        "If empty the key will be valid for any environment",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="keys", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "application",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="project",
                        chained_model_field="project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.application",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.organization",
                    ),
                ),
                (
                    "project",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="organization",
                        chained_model_field="organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.project",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(fields=("event", "name"), name="notification_event_name"),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("event", "name")},
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.UniqueConstraint(fields=("timestamp", "event"), name="occurrence_unique"),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(fields=("slug",), name="org_slug_unique"),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(fields=("slug", "owner"), name="owner_slug_unique"),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("organization", "name"), ("organization", "slug")},
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel"), name="unique_message_for_notification"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(fields=("organization", "project", "name"), name="unique_message_prj"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("organization", "project", "application", "name"), name="unique_message_app"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(fields=("organization", "name"), name="unique_message_org"),
        ),
        migrations.AlterUniqueTogether(
            name="mediafile",
            unique_together={
                ("slug", "organization"),
                ("slug", "organization", "project"),
                ("slug", "organization", "project", "application"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="distributionlist",
            unique_together={("name", "project")},
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", True)),
                fields=("organization", "name"),
                name="bitcaster_channel_org_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                fields=("organization", "project", "name"), name="bitcaster_channel_org_project_app_name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("project", "name"), ("project", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="apikey",
            unique_together={("name", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("organization", "user", "group")},
        ),
    ]
