# Generated by Django 2.2 on 2019-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscription_policy',
            field=models.IntegerField(choices=[(1, 'Free. (Everybody can automatically subscribe)'), (2, 'Invitation. (Require invitation. Event will not be visible)'), (3, 'Members only. (Only members of Application Teams can subscribe)')], default=1),
        ),
    ]
