# Generated by Django 2.2.2 on 2019-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='batch_mode',
            field=models.IntegerField(choices=[(1, 'Start imeddiatly'), (2, 'Start when all notifications are successufully created'), (3, 'Manually start batch, after all notifications are successufully created')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(-1, 'new'), (0, 'pending'), (20, 'retry'), (21, 'remind'), (22, 'waiting confirmation'), (98, 'address not confirmed'), (99, 'expired'), (100, 'completed'), (101, 'confirmed')], db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='status',
            field=models.IntegerField(choices=[(-1, 'new'), (0, 'Running'), (1, 'Aborted'), (2, 'Expired'), (3, 'Paused'), (99, 'Terminated')], default=0),
        ),
    ]
