# Generated by Django 2.2 on 2019-06-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
