# Generated by Django 2.0.6 on 2018-07-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_email',
        ),
    ]
