# Generated by Django 5.1.1 on 2024-09-17 17:46

import django.db.models.deletion
import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0001_initial"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("agent", strategy_field.fields.StrategyField()),
                ("active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict, editable=False)),
                ("data", models.JSONField(blank=True, default=dict, editable=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="bitcaster.event"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitors",
                        to="django_celery_beat.periodictask",
                        verbose_name="Scheduling",
                    ),
                ),
            ],
        ),
    ]
