# Generated by Django 5.0.3 on 2024-04-07 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payload_filter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
