# Generated by Django 2.2 on 2019-06-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('label',)},
        ),
        migrations.RemoveField(
            model_name='address',
            name='code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='valid_for',
        ),
        migrations.RemoveField(
            model_name='address',
            name='verified',
        ),
        migrations.AddField(
            model_name='address',
            name='channels',
            field=models.ManyToManyField(blank=True, through='bitcaster.AddressAssignment', to='bitcaster.Channel'),
        ),
        migrations.AddField(
            model_name='addressassignment',
            name='code',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='addressassignment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addressassignment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='bitcaster.AddressAssignment'),
        ),
        migrations.AlterField(
            model_name='addressassignment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bitcaster.Address'),
        ),
        migrations.AlterField(
            model_name='addressassignment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bitcaster.Channel'),
        ),
        migrations.AlterUniqueTogether(
            name='addressassignment',
            unique_together={('user', 'address', 'channel')},
        ),
    ]
