# Generated by Django 2.2 on 2019-04-08 23:13

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=64, null=True)),
                ('target_object', models.PositiveIntegerField(null=True)),
                ('target_label', models.CharField(blank=True, max_length=300, null=True)),
                ('event', models.IntegerField(choices=[(-1, 'MEMBER_LOGIN'), (-2, 'MEMBER_LOGOUT'), (1, 'MEMBER_EDIT'), (2, 'MEMBER_UPDATE_ADDRESS'), (3, 'MEMBER_DELETE_ADDRESS'), (4, 'MEMBER_ADD_ADDRESS'), (5, 'MEMBER_ADD_ASSIGNMENT'), (6, 'MEMBER_CHANGE_ASSIGNMENT'), (7, 'MEMBER_UPDATE_PROFILE'), (8, 'MEMBER_SUBSCRIBE_EVENT'), (9, 'MEMBER_DELETE_SUBSCRIPTION'), (10, 'MEMBER_TOGGLE_SUBSCRIPTION')])),
                ('ip_address', models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actors', to='bitcaster.User')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitcaster.Organization')),
            ],
        ),
    ]
