# Generated by Django 2.1.7 on 2019-03-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressassignment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='bitcaster.Channel'),
        ),
    ]
