# Generated by Django 2.1.5 on 2019-01-11 22:26

from django.db import migrations, models

import bitcaster.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterField(
            model_name='application',
            name='default_subscription_policy',
            field=bitcaster.db.fields.SubscriptionPolicyField(choices=[(1, 'Free. (Everybody can automatically subscribe)'), (2, 'Require Confirmation. (User can ask to subscribe)'), (3, 'Invitation. (Require invitation. Event will not be visible)'), (4, 'Managed. (User cannot subscribe/unsubscribe but can change channel)')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscription_policy',
            field=bitcaster.db.fields.SubscriptionPolicyField(choices=[(1, 'Free. (Everybody can automatically subscribe)'), (2, 'Require Confirmation. (User can ask to subscribe)'), (3, 'Invitation. (Require invitation. Event will not be visible)'), (4, 'Managed. (User cannot subscribe/unsubscribe but can change channel)')], default=1),
        ),
    ]
