# Generated by Django 5.2.9 on 2025-12-24 16:47

import concurrency.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0002_logentry_member_address_application_channel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("func", models.CharField(max_length=500)),
                ("replace_existing", models.BooleanField(default=False)),
                (
                    "max_instances",
                    models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("next_run_time", models.DateTimeField(blank=True, null=True)),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("interval", "Interval"), ("cron", "Cron")], default="interval", max_length=500
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
