# Generated by Django 5.0.4 on 2024-07-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0002_user_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.occurrence",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="correlation_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
