# Generated by Django 2.2 on 2019-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0002_subscription_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='next_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (20, 'Retry'), (21, 'Remind'), (88, 'Waiting confirmation'), (99, 'Expired'), (100, 'Complete'), (101, 'Confirmed')], db_index=True, default=0),
        ),
    ]
