# Generated by Django 2.2.2 on 2019-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0002_auto_20190611_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Ready'), (-1, 'New'), (0, 'Running'), (1, 'Aborted'), (2, 'Expired'), (3, 'Paused'), (99, 'Terminated')], default=0),
        ),
    ]
