# Generated by Django 2.1.5 on 2019-01-13 00:28

from django.db import migrations, models

import bitcaster.models.subscription


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0002_auto_20190111_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='locked',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(10, 'Admin has sent subscription proposal to user'), (20, 'User has requested the subscripiton'), (30, 'User accepted subscription proposal'), (40, 'Admin approved the subscription request'), (50, 'Admin subscribed user'), (60, 'User subscribed to event')], default=bitcaster.models.subscription.SubscriptionStatus(60)),
        ),
    ]
