# Generated by Django 2.2 on 2019-04-01 23:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0002_logentry_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
