# Generated by Django 2.2 on 2019-06-19 09:16

from django.db import migrations, models

import bitcaster.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0002_auto_20190618_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='address',
        ),
        migrations.AddField(
            model_name='occurence',
            name='processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_expiration',
            field=bitcaster.models.fields.TTLDBField(default=86400, help_text='Time to wait before any pending notification will be canceled. Format: num second|minutes|hour|day. ie. 1d=1 day - 30m=30 minutes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscription_policy',
            field=models.IntegerField(choices=[(1, 'Free. (Everybody can automatically subscribe)'), (2, 'Invitation. (Require invitation. Event will not be visible)'), (4, 'Admin managed. (Only Application Admin can subscribe/unsubscribe)')], default=1),
        ),
    ]
