# Generated by Django 2.1.7 on 2019-03-23 17:44

import django.db.models.deletion
from django.db import migrations, models

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0002_auto_20190322_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=bitcaster.framework.db.fields.RoleField(choices=[(1, 'Owner'), (2, 'Admin'), (4, 'Subscriber')], default=bitcaster.framework.db.fields.Role(4)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_subscriptions', to='bitcaster.Channel'),
        ),
    ]
