# Generated by Django 2.2 on 2019-06-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0003_auto_20190604_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'get_latest_by': 'timestamp', 'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='errorentry',
            old_name='content_type',
            new_name='actor_content_type',
        ),
        migrations.RenameField(
            model_name='errorentry',
            old_name='target_label',
            new_name='actor_label',
        ),
        migrations.RenameField(
            model_name='errorentry',
            old_name='object_id',
            new_name='actor_object_id',
        ),
    ]
