# Generated by Django 5.1.1 on 2024-10-30 08:42

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    Subscription = apps.get_model("bitcaster", "Subscription")
    DistributionlistRecipient = apps.get_model("bitcaster", "DistributionList_recipients")
    for obj in DistributionlistRecipient.objects.all():
        Subscription(distributionlist=obj.distributionlist, assignment=obj.assignment).save()


def backward(apps, schema_editor):
    Subscription = apps.get_model("bitcaster", "Subscription")
    DistributionlistRecipient = apps.get_model("bitcaster", "DistributionList_recipients")
    Distributionlist = apps.get_model("bitcaster", "Distributionlist")
    for obj in Distributionlist.objects.all():
        obj.recipients.remove()
    for obj in Subscription.objects.all():
        DistributionlistRecipient(distributionlist=obj.distributionlist, assignment=obj.assignment).save()


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0003_alter_apikey_key_alter_channel_protocol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config", models.JSONField(default=dict)),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.assignment"),
                ),
                (
                    "distributionlist",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.distributionlist"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distributionlist",
            name="recipients2",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipients2",
                through="bitcaster.Subscription",
                to="bitcaster.assignment",
            ),
        ),
        migrations.RunPython(forward, reverse_code=backward),
    ]
