# Generated by Django 5.2.9 on 2025-12-30 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0003_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="schedule",
        ),
    ]
