# Generated by Django 5.2.2 on 2025-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0003_alter_apikey_key_alter_channel_protocol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
