# Generated by Django 5.1.1 on 2024-10-22 10:56

from django.core.validators import MinValueValidator
from django.db import migrations, models

SQL = "update bitcaster_notification n SET newsletter=ev.newsletter FROM bitcaster_event ev WHERE ev.id=n.event_id"


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0003_alter_apikey_key_alter_channel_protocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="newsletter",
            field=models.BooleanField(default=False, help_text="Do not customise notifications per single user"),
        ),
        migrations.RunSQL(sql=SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="assignment",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name="event",
            name="newsletter",
        ),
        migrations.AddField(
            model_name="channel",
            name="page_size",
            field=models.PositiveIntegerField(blank=True, null=True, validators=[MinValueValidator(1)]),
        ),
    ]
