# Generated by Django 5.0.7 on 2024-08-05 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0003_occurrence_parent_alter_occurrence_correlation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="occurrence_retention",
            field=models.IntegerField(
                blank=True,
                help_text="Number of days (from last update) after which related Occurrences can be purged. If not specified, system default will be used.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
