# Generated by Django 2.2.2 on 2019-06-12 19:51

import django.utils.timezone
from django.db import migrations, models

import bitcaster.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0003_auto_20190611_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='max_events',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='rate',
            field=bitcaster.models.fields.ThrottleField(default='1/s', max_length=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(-1, 'new'), (0, 'queued'), (20, 'retry'), (21, 'remind'), (22, 'waiting confirmation'), (98, 'address not confirmed'), (99, 'expired'), (100, 'completed'), (101, 'confirmed')], db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Ready'), (-2, 'New'), (0, 'Running'), (1, 'Aborted'), (2, 'Expired'), (3, 'Paused'), (99, 'Terminated')], db_index=True, default=0),
        ),
    ]
