# Generated by Django 2.2 on 2019-06-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0003_auto_20190619_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitcaster.DispatcherMetaData'),
        ),
    ]
