# Generated by Django 5.2.9 on 2026-01-04 10:12

import django.contrib.postgres.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0004_remove_monitor_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"ordering": ("name",), "verbose_name": "Api Key", "verbose_name_plural": "Api Keys"},
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ("name",), "verbose_name": "Application", "verbose_name_plural": "Applications"},
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={"ordering": ("name",), "verbose_name": "Channel", "verbose_name_plural": "Channels"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("name",), "verbose_name": "event", "verbose_name_plural": "events"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="monitor",
            options={"ordering": ("name",), "verbose_name": "Monitor", "verbose_name_plural": "Monitors"},
        ),
        migrations.AlterModelOptions(
            name="occurrence",
            options={"ordering": ("timestamp",), "verbose_name": "Occurrence", "verbose_name_plural": "Occurrences"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("console_lock", "Can access Lock console"),
                    ("console_tools", "Can access Tools console"),
                ),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(
                help_text="Label or mnemonic name for this address", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic address"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("account", "Account"),
                ],
                default="GENERIC",
                help_text="Type of address",
                max_length=10,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="value",
            field=models.CharField(help_text="Specific address value.", max_length=255, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="application",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether the application should be active", verbose_name="active"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="auto_crete_event",
            field=models.BooleanField(
                default=False,
                help_text="If true unknown events will be automatically created",
                verbose_name="auto create events",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked any notification is ignored and not forwarded",
                verbose_name="locked",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="paused",
            field=models.BooleanField(
                default=False, help_text="If checked any notification paused", verbose_name="paused"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="subject_prefix",
            field=models.CharField(
                default="[Bitcaster] ",
                help_text="Default prefix for messages supporting subject",
                max_length=50,
                verbose_name="subject prefix",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="config",
            field=models.JSONField(blank=True, default=dict, verbose_name="configuration"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked any notification is ignored and not forwarded",
                verbose_name="locked",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="paused",
            field=models.BooleanField(
                default=False, help_text="If checked any notification paused", verbose_name="paused"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("PLAINTEXT", "Plaintext"),
                    ("SLACK", "Slack"),
                    ("SMS", "Sms"),
                    ("EMAIL", "Email"),
                    ("WEBPUSH", "Webpush"),
                ],
                max_length=50,
                verbose_name="protocol",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked any notification is ignored and not forwarded",
                verbose_name="locked",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="paused",
            field=models.BooleanField(
                default=False, help_text="If checked any notification paused", verbose_name="paused"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="environments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20, null=True),
                blank=True,
                help_text="Allow notification only for these environments",
                null=True,
                size=None,
                verbose_name="environments",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="external_filtering",
            field=models.BooleanField(
                default=False,
                help_text="Allow filtering recipients based on rules passed in the api call",
                verbose_name="external filtering",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="payload_filter",
            field=models.TextField(blank=True, null=True, verbose_name="payload filter"),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="attempts",
            field=models.IntegerField(
                default=5,
                help_text="The remaining number of attempts before the occurrence is marked as failed",
                verbose_name="attempts",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="context",
            field=models.JSONField(
                blank=True, default=dict, help_text="Context provided by the sender", verbose_name="context"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Do not customise notifications per single user",
                verbose_name="newsletter mode",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="recipients",
            field=models.IntegerField(
                default=0, help_text="Total number of reached recipients", verbose_name="recipients"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="status",
            field=models.CharField(
                choices=[("PROCESSED", "Processed"), ("FAILED", "Failed"), ("NEW", "New")],
                default="NEW",
                help_text="Status of the occurrence",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when occurrence has been created.", verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked any notification is ignored and not forwarded",
                verbose_name="locked",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="paused",
            field=models.BooleanField(
                default=False, help_text="If checked any notification paused", verbose_name="paused"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked any notification is ignored and not forwarded",
                verbose_name="locked",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="paused",
            field=models.BooleanField(
                default=False, help_text="If checked any notification paused", verbose_name="paused"
            ),
        ),
    ]
