# Generated by Django 5.1 on 2024-09-01 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcaster", "0004_event_occurrence_retention_alter_application_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="environments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20, null=True),
                blank=True,
                help_text="Limit validity to these environments. If empty the key will be valid for any environment",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(help_text="Label or mnemonic name for this address", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic address"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("account", "Account"),
                ],
                default="GENERIC",
                help_text="Type of address",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="value",
            field=models.CharField(help_text="Specific address value.", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If checked any notification is ignored and not forwarded"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If checked any notification is ignored and not forwarded"
            ),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="recipients",
            field=models.ManyToManyField(blank=True, to="bitcaster.assignment"),
        ),
        migrations.AlterField(
            model_name="event",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If checked any notification is ignored and not forwarded"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="environments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20, null=True),
                blank=True,
                help_text="Allow notification only for these environments",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If checked any notification is ignored and not forwarded"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If checked any notification is ignored and not forwarded"
            ),
        ),
    ]
