# Generated by Django 2.2 on 2019-06-06 07:18

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0004_auto_20190605_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=bitcaster.framework.db.fields.RetrieverField(blank=True, null=True, verbose_name='Retriever'),
        ),
        migrations.CreateModel(
            name='FileGetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('config', bitcaster.framework.db.fields.EncryptedJSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('handler', bitcaster.framework.db.fields.RetrieverField(null=True, verbose_name='Retriever')),
                ('deprecated', models.BooleanField(default=False)),
                ('errors_threshold', models.IntegerField(default=100, help_text='Number or errors before channel will be automatically disabled')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitcaster.Application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitcaster.Organization')),
            ],
            options={
                'verbose_name': 'FileGetter',
                'verbose_name_plural': 'FileGetters',
                'ordering': ('name',),
                'unique_together': {('organization', 'application', 'name')},
            },
        ),
    ]
