# Generated by Django 2.2 on 2019-06-13 09:13

from django.db import migrations, models

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0004_auto_20190612_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='data',
            field=bitcaster.framework.db.fields.EncryptedJSONField(default=dict),
        ),
        migrations.AddField(
            model_name='monitor',
            name='events',
            field=models.PositiveIntegerField(default=0, help_text='Current number of triggered events'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='event',
            field=models.IntegerField(choices=[(0, 'MEMBER_LOGIN'), (1, 'MEMBER_LOGOUT'), (101, 'APPLICATION_CREATED'), (102, 'APPLICATION_UPDATED'), (103, 'APPLICATION_DELETED'), (104, 'APPLICATION_ENABLED'), (105, 'APPLICATION_DISABLED'), (201, 'INVITATION_CREATED'), (202, 'INVITATION_SENT'), (203, 'INVITATION_ACCEPTED'), (601, 'MEMBERSHIP_CREATED'), (302, 'MEMBER_UPDATE_PROFILE'), (311, 'ADDRESS_CREATED'), (312, 'ADDRESS_UPDATED'), (313, 'ADDRESS_DELETED'), (314, 'ADDRESS_VERIFIED'), (401, 'ASSIGNMENT_CREATED'), (402, 'ASSIGNMENT_UPDATED'), (403, 'ASSIGNMENT_DELETED'), (505, 'SUBSCRIPTION_CREATED'), (506, 'SUBSCRIPTION_UPDATED'), (507, 'SUBSCRIPTION_DELETED'), (801, 'CHANNEL_CREATED'), (802, 'CHANNEL_UPDATED'), (803, 'CHANNEL_DELETED'), (804, 'CHANNEL_ENABLED'), (805, 'CHANNEL_DISABLED'), (806, 'CHANNEL_DEPRECATED'), (901, 'EVENT_CREATED'), (902, 'EVENT_UPDATED'), (903, 'EVENT_DELETED'), (904, 'EVENT_ENABLED'), (905, 'EVENT_DISABLED'), (906, 'EVENT_DEV_MODE_ON'), (907, 'EVENT_DEV_MODE_OFF'), (1001, 'MONITOR_CREATED'), (1002, 'MONITOR_UPDATED'), (1003, 'MONITOR_DELETED'), (1004, 'MONITOR_ENABLED'), (1005, 'MONITOR_DISABLED'), (1006, 'MONITOR_TERMINATED')]),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='max_events',
            field=models.PositiveIntegerField(blank=True, help_text='Max total number of events to trigger', null=True),
        ),
    ]
