# Generated by Django 2.2 on 2019-06-19 16:49

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Channel = apps.get_model('bitcaster', 'Channel')
    db_alias = schema_editor.connection.alias
    for ch in Channel.objects.using(db_alias).all():
        ch.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('bitcaster', '0004_channel_metadata'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),

    ]
