# Generated by Django 5.2.2 on 2025-12-08 07:11

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0004_alter_assignment_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="status",
            field=models.CharField(
                choices=[("NEW", "New"), ("PROCESSED", "Processed"), ("FAILED", "Failed")],
                default="NEW",
                help_text="Status of the occurrence",
                max_length=20,
            ),
        ),
    ]
