# Generated by Django 5.2.9 on 2026-01-06 12:59

import concurrency.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0005_alter_apikey_options_alter_application_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("PLAINTEXT", "Plaintext"),
                    ("SLACK", "Slack"),
                    ("SMS", "Sms"),
                    ("EMAIL", "Email"),
                    ("WEBPUSH", "Webpush"),
                    ("INTERNAL", "Internal"),
                ],
                max_length=50,
                verbose_name="protocol",
            ),
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "CRITICAL"),
                            ("FATAL", "FATAL"),
                            ("ERROR", "ERROR"),
                            ("WARN", "WARN"),
                            ("WARNING", "WARNING"),
                            ("INFO", "INFO"),
                            ("DEBUG", "DEBUG"),
                            ("NOTSET", "NOTSET"),
                        ],
                        default=20,
                        max_length=255,
                    ),
                ),
                ("subject", models.TextField()),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("read", models.DateTimeField(blank=True, default=None, null=True)),
                ("displayed", models.BooleanField(blank=True, default=None, null=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bitcaster.event")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitcaster_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Message",
                "verbose_name_plural": "User Messages",
            },
        ),
    ]
