# Generated by Django 5.2.2 on 2025-12-13 15:58

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models

import bitcaster.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0005_alter_channel_project_alter_occurrence_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bitcaster.user",),
            managers=[
                ("objects", bitcaster.models.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="dynamic",
            field=models.BooleanField(
                default=False,
                help_text="Dynamic notification do not need DistributionList. "
                "It filters users based on 'recipients_filter' rules",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients_filter",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="application",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="project",
                chained_model_field="project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.application",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="parent",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.channel",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="application",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="project",
                chained_model_field="project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.application",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="application",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="project",
                chained_model_field="project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.application",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="recipients",
            field=models.IntegerField(default=0, help_text="Total number of reached recipients"),
        ),
    ]
