# Generated by Django 2.2 on 2019-06-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0005_auto_20190606_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitcaster.FileGetter'),
        ),
        migrations.AlterField(
            model_name='filegetter',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filegetters', to='bitcaster.Application'),
        ),
        migrations.AlterField(
            model_name='filegetter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filegetters', to='bitcaster.Organization'),
        ),
    ]
