# Generated by Django 2.2 on 2019-06-15 09:23

from django.db import migrations

import bitcaster.framework.db.fields
import bitcaster.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0005_auto_20190613_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extras',
            field=bitcaster.framework.db.fields.EncryptedJSONField(blank=True, default=dict, null=True, verbose_name='extras'),
        ),
        migrations.AddField(
            model_name='user',
            name='options',
            field=bitcaster.framework.db.fields.EncryptedJSONField(blank=True, default=dict, null=True, verbose_name='options'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='rate',
            field=bitcaster.models.fields.ThrottleField(default='1/m', max_length=10, validators=[bitcaster.models.fields.MinRateValidator('1/m')]),
        ),
    ]
