# Generated by Django 2.2 on 2019-06-06 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0006_auto_20190606_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
