# Generated by Django 5.2.9 on 2026-01-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0006_alter_channel_protocol_usermessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="bitcaster.event"
            ),
        ),
    ]
