# Generated by Django 2.2 on 2019-06-15 09:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0006_auto_20190615_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='extras'),
        ),
    ]
