# Generated by Django 5.2.2 on 2025-12-14 16:32

from django.db import migrations

import bitcaster.models.log


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("bitcaster", "0006_member_notification_dynamic_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntry",
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[],
            options={
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", bitcaster.models.log.LogEntryManager()),
            ],
        ),
    ]
