# Generated by Django 2.2 on 2019-06-15 19:07

import django.core.validators
from django.db import migrations, models

import bitcaster.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0007_auto_20190615_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationtriggerkey',
            name='all_events',
            field=models.BooleanField(default=False, help_text='If checked, the key is valid even those events created later'),
        ),
        migrations.AlterField(
            model_name='applicationtriggerkey',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='applicationtriggerkey',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='dispatch_page_size',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='dispatcher page size'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='dispatch_rate',
            field=bitcaster.models.fields.ThrottleField(default='1/s', max_length=10, verbose_name='dispatch rate'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscription_policy',
            field=models.IntegerField(choices=[(1, 'Free. (Everybody can automatically subscribe)'), (2, 'Invitation. (Require invitation. Event will not be visible)'), (3, 'Members only. (Only members of Application Teams can subscribe)'), (4, 'Admin managed. (Only Application Admin can subscribe/unsubscribe)')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(10, 'Subscription process is not completed'), (60, 'User subscribed to event'), (50, 'Admin subscribed user. Subscription is locked')], default=60),
        ),
    ]
