# Generated by Django 2.2 on 2019-06-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0007_notification_attachments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('channel', 'occurence', 'address')},
        ),
    ]
