# Generated by Django 5.2.2 on 2025-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0007_delete_logentry_logentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="external_filtering",
            field=models.BooleanField(
                default=False, help_text="Allow filtering recipients based on rules passed in the api call"
            ),
        ),
    ]
