# Generated by Django 5.2.10 on 2026-01-09 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0007_alter_usermessage_event"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="MessageTemplate",
        ),
    ]
