# Generated by Django 5.2.10 on 2026-01-11 07:32

from django.db import migrations, models

import bitcaster.models.key


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0008_rename_message_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="debug",
            field=models.BooleanField(
                default=False, help_text="Allow debug information in teh message", verbose_name="debug allowed"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="grants",
            field=bitcaster.models.key.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FULL_ACCESS", "Full Access"),
                        ("SYSTEM_PING", "Ping"),
                        ("USER_READ", "User Read"),
                        ("USER_PROFILE", "Read User Profile and emssages"),
                        ("USER_WRITE", "User Write"),
                        ("ORG_READ", "Organization Read"),
                        ("APPLICATION_ADMIN", "Application Admin"),
                        ("EVENT_LIST", "Event list"),
                        ("EVENT_TRIGGER", "Event Trigger"),
                        ("EVENT_AUTO_CREATE", "Event Auto-Create"),
                        ("DISTRIBUTION_LIST", "Distribution list"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
