# Generated by Django 2.2 on 2019-06-06 12:08

import django.contrib.postgres.fields
from django.db import migrations

import bitcaster.models.notification


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0008_auto_20190606_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=bitcaster.models.notification.AttachmentField(), blank=True, null=True, size=None),
        ),
    ]
