# Generated by Django 5.2.2 on 2025-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0008_notification_external_filtering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("console_lock", "Can access Lock console"),
                    ("console_tools", "Can access Tools console"),
                ),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="paused",
            field=models.BooleanField(default=False, help_text="If checked any notification paused"),
        ),
        migrations.AddField(
            model_name="channel",
            name="paused",
            field=models.BooleanField(default=False, help_text="If checked any notification paused"),
        ),
        migrations.AddField(
            model_name="event",
            name="paused",
            field=models.BooleanField(default=False, help_text="If checked any notification paused"),
        ),
        migrations.AddField(
            model_name="project",
            name="paused",
            field=models.BooleanField(default=False, help_text="If checked any notification paused"),
        ),
        migrations.AddField(
            model_name="user",
            name="paused",
            field=models.BooleanField(default=False, help_text="If checked any notification paused"),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="status",
            field=models.CharField(
                choices=[("PROCESSED", "Processed"), ("FAILED", "Failed"), ("NEW", "New")],
                default="NEW",
                help_text="Status of the occurrence",
                max_length=20,
            ),
        ),
    ]
