# Generated by Django 5.2.10 on 2026-01-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0009_messagetemplate_debug_alter_apikey_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("%Y-%m-%d", "2026-01-12"),
                    ("%Y %b %d", "2026 Jan 12"),
                    ("%d %b %Y", "12 Jan 2026"),
                    ("%d %B %Y", "12 January 2026"),
                    ("%B %d %Y", "January 12 2026"),
                ],
                default="%Y-%m-%d",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_time_format",
            field=models.CharField(
                choices=[
                    ("%Y-%m-%d %H:%M", "2026-01-12 08:27"),
                    ("%Y %b %d %H:%M", "2026 Jan 12 08:27"),
                    ("%d %b %Y %H:%M", "12 Jan 2026 08:27"),
                    ("%d %B %Y %H:%M", "12 January 2026 08:27"),
                    ("%B %d %Y %H:%M", "January 12 2026 08:27"),
                ],
                default="%Y-%m-%d %H:%M",
                max_length=50,
            ),
        ),
    ]
