# Generated by Django 5.2.2 on 2025-12-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0009_alter_user_options_application_paused_channel_paused_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
