# Generated by Django 2.2 on 2019-06-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0009_auto_20190606_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditlog', to='bitcaster.Application'),
        ),
    ]
