# Generated by Django 5.2.10 on 2026-01-12 08:30

from django.db import migrations, models

import bitcaster.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0009_messagetemplate_debug_alter_apikey_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=bitcaster.models.user.get_date_format_choices, default="%Y-%m-%d", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_time_format",
            field=models.CharField(
                choices=bitcaster.models.user.get_datetime_format_choices, default="%Y-%m-%d %H:%M", max_length=50
            ),
        ),
    ]
