# Generated by Django 5.2.9 on 2025-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0010_notification_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="auto_crete_event",
            field=models.BooleanField(default=False, help_text="If true unknown events will be automatically created"),
        ),
    ]
