# Generated by Django 2.2 on 2019-06-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bitcaster', '0010_auditlogentry_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorentry',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='errorentry',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (20, 'Retry'), (21, 'Remind'), (88, 'Waiting confirmation'), (98, 'Address not confirmed'), (99, 'Expired'), (100, 'Complete'), (101, 'Confirmed')], db_index=True, default=0),
        ),
    ]
