# Generated by Django 5.2.10 on 2026-01-12 20:07

from django.db import migrations, models

import bitcaster.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0010_user_date_format_user_date_time_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=bitcaster.models.user.get_time_format_choices,
                default=["%H:%M", "%H:%M %Z", "%I:%M%p %Z", "%I:%M%p"],
                max_length=50,
            ),
        ),
    ]
