# Generated by Django 2.2 on 2019-06-07 13:13

import django.db.models.deletion
import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0011_auto_20190606_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='valid_for',
            field=strategy_field.fields.MultipleStrategyField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='bitcaster.Address'),
        ),
    ]
