# Generated by Django 5.2.10 on 2026-02-10 10:29

import uuid

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0011_user_time_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="advanced_configuration",
            field=models.JSONField(
                blank=True, default=dict, help_text="Advanced configuration, i.e. for attachment support", null=True
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "correlation_id",
                    models.SlugField(blank=True, default=uuid.uuid4, help_text="Correlation ID", unique=True),
                ),
                ("document", models.FileField(help_text="Attachment file", upload_to="attachments/")),
                ("mime_type", models.CharField(help_text="Attachment MIME type", max_length=256)),
                ("size", models.PositiveIntegerField(default=0, help_text="Attachment size in bytes")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="bitcaster.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
