# Generated by Django 5.2.11 on 2026-03-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0012_application_advanced_configuration_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("PLAINTEXT", "Plaintext"),
                    ("SLACK", "Slack"),
                    ("SMS", "Sms"),
                    ("EMAIL", "Email"),
                    ("WEBPUSH", "Webpush"),
                    ("INTERNAL", "Internal"),
                    ("MARKDOWN", "Markdown"),
                ],
                max_length=50,
                verbose_name="protocol",
            ),
        ),
    ]
