# Generated by Django 2.2 on 2019-06-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bitcaster', '0012_auto_20190607_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlogentry',
            old_name='target_object',
            new_name='target_object_id',
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='event',
            field=models.IntegerField(choices=[(0, 'MEMBER_LOGIN'), (1, 'MEMBER_LOGOUT'), (201, 'INVITATION_CREATED'), (202, 'INVITATION_SENT'), (203, 'INVITATION_ACCEPTED'), (301, 'MEMBER_UPDATE_PROFILE'), (302, 'MEMBER_UPDATE_ADDRESS'), (303, 'MEMBER_DELETE_ADDRESS'), (304, 'MEMBER_ADD_ADDRESS'), (305, 'MEMBER_VALIDATE_ADDRESS'), (401, 'MEMBER_ADD_ASSIGNMENT'), (402, 'MEMBER_CHANGE_ASSIGNMENT'), (403, 'MEMBER_DELETE_ASSIGNMENT'), (505, 'MEMBER_SUBSCRIBE_EVENT'), (506, 'MEMBER_DELETE_SUBSCRIPTION'), (507, 'MEMBER_ENABLE_SUBSCRIPTION'), (601, 'MEMBERSHIP_CREATED'), (800, 'CHANNEL_DEPRECATED'), (801, 'CHANNEL_DELETED')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bitcaster.User'),
        ),
    ]
