# Generated by Django 2.2 on 2019-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0013_auto_20190608_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='event',
            field=models.IntegerField(choices=[(0, 'MEMBER_LOGIN'), (1, 'MEMBER_LOGOUT'), (201, 'INVITATION_CREATED'), (202, 'INVITATION_SENT'), (203, 'INVITATION_ACCEPTED'), (301, 'MEMBER_UPDATE_PROFILE'), (302, 'MEMBER_UPDATE_ADDRESS'), (303, 'MEMBER_DELETE_ADDRESS'), (304, 'MEMBER_ADD_ADDRESS'), (305, 'MEMBER_VALIDATE_ADDRESS'), (401, 'MEMBER_ADD_ASSIGNMENT'), (402, 'MEMBER_CHANGE_ASSIGNMENT'), (403, 'MEMBER_DELETE_ASSIGNMENT'), (505, 'MEMBER_SUBSCRIBE_EVENT'), (506, 'MEMBER_DELETE_SUBSCRIPTION'), (507, 'MEMBER_ENABLE_SUBSCRIPTION'), (601, 'MEMBERSHIP_CREATED'), (800, 'CHANNEL_DEPRECATED'), (801, 'CHANNEL_DELETED'), (802, 'CHANNEL_ENABLED'), (803, 'CHANNEL_DISABLED'), (804, 'CHANNEL_UPDATED'), (805, 'CHANNEL_CREATED')]),
        ),
    ]
