# Generated by Django 5.2.11 on 2026-03-21 09:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0013_alter_channel_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="Filename to use when downloading the attachment",
                max_length=256,
                null=True,
                verbose_name="Filename",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="correlation_id",
            field=models.SlugField(
                blank=True,
                default=uuid.uuid4,
                help_text="Unique human readable identifier for the attachment",
                unique=True,
                verbose_name="Correlation ID",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(
                help_text="MIME type of the file. It will be auto-detected if not provided", max_length=256
            ),
        ),
    ]
