# Generated by Django 2.2 on 2019-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0014_auto_20190608_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='development_mode',
            field=models.BooleanField(default=False, help_text='Only Admins will receive events'),
        ),
    ]
