# Generated by Django 5.2.11 on 2026-03-28 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0014_attachment_filename_alter_attachment_correlation_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="auto_crete_event",
            new_name="auto_create_event",
        ),
    ]
