# Generated by Django 5.2.11 on 2026-04-05 08:45

import django.utils.timezone
from django.db import migrations, models

import bitcaster.models.process_log
import bitcaster.models.task


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0015_rename_auto_crete_event_application_auto_create_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessLogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_time",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="action time"),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(10, "Success"), (20, "Failure")], default=10, verbose_name="status"),
                ),
                ("elapsed", models.IntegerField(blank=True, null=True, verbose_name="elapsed")),
                ("task_name", models.CharField(blank=True, max_length=100, null=True)),
                ("task_func", models.CharField(blank=True, max_length=500, null=True)),
                ("args", models.JSONField(blank=True, null=True)),
                ("kwargs", models.JSONField(blank=True, null=True)),
                ("exc_info", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name": "process log entry",
                "verbose_name_plural": "process log entries",
            },
            managers=[
                ("objects", bitcaster.models.process_log.LogEntryManager()),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="auto_create_options",
            field=models.IntegerField(
                choices=[
                    (100, "Create eevent and process"),
                    (10, "Create eevent and set it not active"),
                    (20, "Create eevent and set it paused"),
                    (30, "Create event but do not trigger it"),
                ],
                default=10,
                help_text="If true unknown events will be automatically created",
                verbose_name="auto create event options",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="func",
            field=models.CharField(choices=bitcaster.models.task.get_tasks, max_length=500),
        ),
    ]
