# Generated by Django 5.2.11 on 2026-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0016_processlogentry_application_auto_create_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="context_filter",
            field=models.JSONField(blank=True, default=dict, verbose_name="context filter"),
        ),
        migrations.AddField(
            model_name="notification",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="notification",
            name="policy",
            field=models.IntegerField(
                choices=[
                    (1, "Default"),
                    (2, "Context based filtering"),
                    (3, "External ruled filtering"),
                    (4, "Fixed ruled filtering"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="auto_create_options",
            field=models.IntegerField(
                choices=[
                    (100, "Create eevent and process"),
                    (10, "Create eevent and set it not active"),
                    (20, "Create eevent and set it paused"),
                    (30, "Create event but do not trigger it"),
                ],
                default=100,
                help_text="If true unknown events will be automatically created",
                verbose_name="auto create event options",
            ),
        ),
    ]
