# Generated by Django 2.2.2 on 2019-06-08 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0016_auto_20190608_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', bitcaster.framework.db.fields.EncryptedPickledObjectField(editable=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitcaster.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
