# Generated by Django 2.2.2 on 2019-06-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0017_organizationoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationoption',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bitcaster.Organization'),
        ),
    ]
