# Generated by Django 5.2.11 on 2026-04-10 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0018_notification_policy_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="dynamic",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="external_filtering",
        ),
    ]
