# Generated by Django 2.2.2 on 2019-06-08 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0018_auto_20190608_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationoption',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bitcaster.Organization'),
        ),
    ]
