# Generated by Django 5.2.11 on 2026-04-17 20:32

import concurrency.fields
import django.contrib.postgres.fields
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
import strategy_field.fields
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models

import bitcaster.models.key
import bitcaster.models.media
import bitcaster.models.task
import bitcaster.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0019_remove_notification_dynamic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="context_filter",
        ),
        migrations.AlterField(
            model_name="address",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="address",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                help_text="owner of this address",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="environments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20, null=True),
                blank=True,
                help_text="Limit validity to these environments. If empty the key will be valid for any environment",
                null=True,
                size=None,
                verbose_name="Environments",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="grants",
            field=bitcaster.models.key.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FULL_ACCESS", "Full Access"),
                        ("SYSTEM_PING", "Ping"),
                        ("USER_READ", "User Read"),
                        ("USER_PROFILE", "Read User Profile and emssages"),
                        ("USER_WRITE", "User Write"),
                        ("ORG_READ", "Organization Read"),
                        ("APPLICATION_ADMIN", "Application Admin"),
                        ("EVENT_LIST", "Event list"),
                        ("EVENT_TRIGGER", "Event Trigger"),
                        ("EVENT_AUTO_CREATE", "Event Auto-Create"),
                        ("DISTRIBUTION_LIST", "Distribution list"),
                    ],
                    max_length=255,
                ),
                blank=True,
                help_text="grants for this key",
                null=True,
                size=None,
                verbose_name="Grants",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default=bitcaster.models.key.make_token,
                help_text="api key",
                max_length=255,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(
                db_collation="case_insensitive",
                db_index=True,
                help_text="name of his key",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.organization",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                help_text="Project this record belong to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                help_text="user responsible of this key",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="advanced_configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Advanced configuration, i.e. for attachment support",
                null=True,
                verbose_name="Advanced configuration",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="application",
            name="from_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="default from address for emails",
                max_length=254,
                verbose_name="From email",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(help_text="name", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="owner of this application",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="project",
            field=models.ForeignKey(
                help_text="project this application belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="bitcaster.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="slug",
            field=models.SlugField(blank=True, help_text="record slug", max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="application",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="active",
            field=models.BooleanField(default=True, help_text="If the assignment is acive", verbose_name="Validated"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="address",
            field=models.ForeignKey(
                help_text="address to use for this assignment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="bitcaster.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="channel",
            field=models.ForeignKey(
                help_text="channel to assign to the semected address",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="bitcaster.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="system data of this assignment", verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="validated",
            field=models.BooleanField(
                default=False, help_text="If the assignment has been validated", verbose_name="Validated"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="application",
            field=models.ForeignKey(
                help_text="application owner of this Attachment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="bitcaster.application",
                verbose_name="Application",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="document",
            field=models.FileField(help_text="Attachment file", upload_to="attachments/", verbose_name="Document/File"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(
                help_text="MIME type of the file. It will be auto-detected if not provided",
                max_length=256,
                verbose_name="MIME Type",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="size",
            field=models.PositiveIntegerField(
                default=0, help_text="Attachment size in bytes", verbose_name="File size"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="active",
            field=models.BooleanField(default=True, help_text="enable/disable channel", verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Channel configuration", verbose_name="configuration"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="dispatcher",
            field=strategy_field.fields.StrategyField(
                default="test", help_text="channel dispatcher", verbose_name="Dispatcher"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(help_text="channel name", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Chanel organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="parent",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                help_text="parent channel",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.channel",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                help_text="project linked to this channel",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("PLAINTEXT", "Plaintext"),
                    ("SLACK", "Slack"),
                    ("SMS", "Sms"),
                    ("EMAIL", "Email"),
                    ("WEBPUSH", "Webpush"),
                    ("INTERNAL", "Internal"),
                    ("MARKDOWN", "Markdown"),
                ],
                help_text="channel protocol",
                max_length=50,
                verbose_name="protocol",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="name",
            field=models.CharField(
                db_collation="case_insensitive",
                help_text="name of this distribuition list",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="project",
            field=models.ForeignKey(
                help_text="project linked to this distribution list",
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, help_text="members of the list", to="bitcaster.assignment", verbose_name="Recipients"
            ),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="active",
            field=models.BooleanField(
                default=True, help_text="enable/disable event notifications", verbose_name="active"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="application",
            field=models.ForeignKey(
                help_text="application linked to this event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="bitcaster.application",
                verbose_name="Application",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="list of channels enabled fot this event",
                to="bitcaster.channel",
                verbose_name="Channels",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                blank=True, help_text="description of the event", max_length=255, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(help_text="name", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Do not customise notifications per single user",
                verbose_name="Newsletter mode",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="occurrence_retention",
            field=models.IntegerField(
                blank=True,
                help_text="Number of days (from last update) after which related Occurrences can be purged. "
                "If not specified, system default will be used.",
                null=True,
                verbose_name="Occurrence retention",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, help_text="record slug", max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="event",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="application",
            field=models.ForeignKey(
                help_text="application linked to this message",
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.application",
                verbose_name="Application",
            ),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="date of this message", verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="level",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "CRITICAL"),
                    ("FATAL", "FATAL"),
                    ("ERROR", "ERROR"),
                    ("WARN", "WARN"),
                    ("WARNING", "WARNING"),
                    ("INFO", "INFO"),
                    ("DEBUG", "DEBUG"),
                    ("NOTSET", "NOTSET"),
                ],
                help_text="Log message level",
                max_length=255,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="message",
            field=models.TextField(help_text="message body", verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="file_type",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="File type"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="image height in pixels", null=True, verbose_name="Image height"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="image",
            field=bitcaster.models.media.ImageFieldWithExtra(
                height_field="height",
                help_text="Media file",
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Image",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="mime_type",
            field=models.CharField(
                blank=True, default="", help_text="Mime type", max_length=100, verbose_name="Mime type"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="name",
            field=models.CharField(help_text="name", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.organization",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                help_text="Project this record belong to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="size",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="image size in bytes", null=True, verbose_name="Image size"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="slug",
            field=models.SlugField(blank=True, help_text="record slug", max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="image width in pixels", null=True, verbose_name="Image width"
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="name",
            field=models.CharField(help_text="name of this template message", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.organization",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="project",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="organization",
                chained_model_field="organization",
                help_text="Project this record belong to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.project",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="active",
            field=models.BooleanField(default=True, help_text="Enable/Disable monitor", verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="agent",
            field=strategy_field.fields.StrategyField(help_text="Agent to use", verbose_name="Agent"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="async_result",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="async_result",
                max_length=255,
                verbose_name="async_result",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="monitor configuration",
                verbose_name="Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, editable=False, help_text="monitor daa", verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="bitcaster.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="name",
            field=models.CharField(help_text="name for this monitor", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="result",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="monitor last execution result",
                verbose_name="Latest result",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=False, help_text="If this notification is active", verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.TextField(
                blank=True, help_text="Small description of this notification", null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="distribution",
            field=models.ForeignKey(
                blank=True,
                help_text="Distribution to use for this notification. Can be empty depending on the policy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="bitcaster.distributionlist",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                help_text="Event linked to this notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="bitcaster.event",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="extra_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra context to add to what provided by the sender",
                verbose_name="Extra context",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="name",
            field=models.CharField(help_text="Notification name", max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="payload_filter",
            field=models.TextField(
                blank=True,
                help_text="YAML configuration to filter notifications based on event data. "
                "Use JMESPath expressions to match payload values. "
                "Supports logical operators (AND, OR, NOT). "
                "If the payload does not match the rules, the notification is skipped.",
                null=True,
                verbose_name="payload filter",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="policy",
            field=models.IntegerField(
                choices=[
                    (1, "No Filters. Forward to distribution list"),
                    (3, "API filters. Do not use DistributionList, filter users by API rules"),
                    (4, "Filter users using provided rules."),
                ],
                default=1,
                help_text="Routing policy",
                verbose_name="policy",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipients_filter",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON structure to dynamically select recipients. "
                "Use 'include' and 'exclude' keys with Django-style lookups "
                "(e.g., {'email__endswith': '@company.com'}). "
                "Supports nested lists for complex AND/OR logic.",
                verbose_name="recipients filter",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="correlation_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Correlation ID provided by the sender",
                max_length=255,
                null=True,
                verbose_name="Correlation ID",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="data",
            field=models.JSONField(
                default=dict, help_text="Information about the processing (recipients, channels)", verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Options provided by the sender to route linked notifications",
                verbose_name="Options",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="from_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="default from address for emails",
                max_length=254,
                verbose_name="From email",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(help_text="name", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, help_text="record slug", max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="action_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, help_text="Action time", verbose_name="action time"
            ),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="args",
            field=models.JSONField(blank=True, help_text="Task arguments", null=True, verbose_name="args"),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="elapsed",
            field=models.IntegerField(blank=True, help_text="Elapsed time", null=True, verbose_name="elapsed"),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="exc_info",
            field=models.TextField(
                blank=True, default="", help_text="Exception info", null=True, verbose_name="Exc Info"
            ),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="kwargs",
            field=models.JSONField(blank=True, help_text="Task keyword arguments", null=True, verbose_name="kwargs"),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="status",
            field=models.IntegerField(
                choices=[(10, "Success"), (20, "Failure")], default=10, help_text="Status", verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="task_func",
            field=models.CharField(
                blank=True, help_text="Task full path", max_length=500, null=True, verbose_name="task func"
            ),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="task_name",
            field=models.CharField(
                blank=True, help_text="Task name", max_length=100, null=True, verbose_name="task name"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="project",
            name="environments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20, null=True),
                blank=True,
                help_text="Environments available for project",
                null=True,
                size=None,
                verbose_name="Environments",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="from_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="default from address for emails",
                max_length=254,
                verbose_name="From Email",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(help_text="name", max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="bitcaster.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, help_text="record slug", max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="active",
            field=models.BooleanField(default=False, help_text="Active", verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="task",
            name="args",
            field=models.JSONField(blank=True, default=list, help_text="Args", verbose_name="Args"),
        ),
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="task",
            name="func",
            field=models.CharField(
                choices=bitcaster.models.task.get_tasks, help_text="Func", max_length=500, verbose_name="Func"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="kwargs",
            field=models.JSONField(blank=True, default=dict, help_text="Kwargs", verbose_name="Kwargs"),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Last updated", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="task",
            name="max_instances",
            field=models.IntegerField(
                default=1,
                help_text="Max instances",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Max instances",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(help_text="Name", max_length=200, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="next_run_time",
            field=models.DateTimeField(blank=True, help_text="Next run time", null=True, verbose_name="Next run time"),
        ),
        migrations.AlterField(
            model_name="task",
            name="replace_existing",
            field=models.BooleanField(default=False, help_text="Replace existing", verbose_name="Replace existing"),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(help_text="Slug", unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="task",
            name="trigger",
            field=models.CharField(
                choices=[("interval", "Interval"), ("cron", "Cron")],
                default="interval",
                help_text="Trigger",
                max_length=500,
                verbose_name="Trigger",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="trigger_config",
            field=models.JSONField(blank=True, default=dict, help_text="Trigger config", verbose_name="Trigger config"),
        ),
        migrations.AlterField(
            model_name="task",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="user",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="User custom fields", verbose_name="Custom fields"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=bitcaster.models.user.get_date_format_choices,
                default="%Y-%m-%d",
                help_text="User preferred date only format",
                max_length=50,
                verbose_name="Date format",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_time_format",
            field=models.CharField(
                choices=bitcaster.models.user.get_datetime_format_choices,
                default="%Y-%m-%d %H:%M",
                help_text="User preferred date and time format",
                max_length=50,
                verbose_name="Date and time format",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=bitcaster.models.user.get_time_format_choices,
                default=["%H:%M", "%H:%M %Z", "%I:%M%p %Z", "%I:%M%p"],
                help_text="User time only format",
                max_length=50,
                verbose_name="Time format",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                default="UTC", help_text="User time zone", verbose_name="Timezone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Message date", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="displayed",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="If the message has beed displayed to teh user",
                null=True,
                verbose_name="Displayed",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event produced the message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcaster.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="level",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "CRITICAL"),
                    ("FATAL", "FATAL"),
                    ("ERROR", "ERROR"),
                    ("WARN", "WARN"),
                    ("WARNING", "WARNING"),
                    ("INFO", "INFO"),
                    ("DEBUG", "DEBUG"),
                    ("NOTSET", "NOTSET"),
                ],
                default=20,
                help_text="Level of the message",
                max_length=255,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="message",
            field=models.TextField(help_text="Content of the message", verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="read",
            field=models.DateTimeField(
                blank=True, default=None, help_text="Read date", null=True, verbose_name="Readed om"
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="subject",
            field=models.TextField(help_text="Subject of the message", verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bitcaster_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, help_text="Record last update time", verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="version number of the record", verbose_name="Version"
            ),
        ),
    ]
