# Generated by Django 2.2.2 on 2019-06-08 20:57

from django.db import migrations

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0019_auto_20190608_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='storage',
            field=bitcaster.framework.db.fields.EncryptedJSONField(default=dict, verbose_name='storage'),
        ),
    ]
