# Generated by Django 2.2.2 on 2019-06-08 21:09

from django.db import migrations

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0020_organization_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='storage',
            field=bitcaster.framework.db.fields.EncryptedJSONField(default=dict, verbose_name='storage'),
        ),
    ]
