# Generated by Django 5.2.13 on 2026-04-21 14:33

from django.db import migrations, models

import bitcaster.models.choices
import bitcaster.models.notification
import bitcaster.models.process_log


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0020_remove_notification_context_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmessage",
            name="level",
            field=models.CharField(
                choices=bitcaster.models.choices.get_logging_levels,
                help_text="Log message level",
                max_length=255,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="policy",
            field=models.IntegerField(
                choices=bitcaster.models.notification.get_policy,
                default=1,
                help_text="Routing policy",
                verbose_name="policy",
            ),
        ),
        migrations.AlterField(
            model_name="processlogentry",
            name="status",
            field=models.IntegerField(
                choices=bitcaster.models.process_log._get_status_choices,
                default=10,
                help_text="Status",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="level",
            field=models.CharField(
                choices=bitcaster.models.choices.get_logging_levels,
                default=20,
                help_text="Level of the message",
                max_length=255,
                verbose_name="Level",
            ),
        ),
    ]
