# Generated by Django 2.2.2 on 2019-06-09 12:44

import django.db.models.deletion
from django.db import migrations, models

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0021_application_storage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationMember',
            new_name='ApplicationUser')
    ]
