# Generated by Django 5.2.16 on 2026-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0021_alter_logmessage_level_alter_notification_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="If the assignment is acive",
                verbose_name="Active",
            ),
        ),
    ]
