# Generated by Django 2.2.2 on 2019-06-09 15:26

from django.db import migrations, models

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0022_auto_20190609_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='development_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='role',
            field=bitcaster.framework.db.fields.ApplicationRoleField(choices=[(100, 'Admin'), (101, 'User')], default=101),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='event',
            field=models.IntegerField(choices=[(0, 'MEMBER_LOGIN'), (1, 'MEMBER_LOGOUT'), (101, 'APPLICATION_CREATED'), (102, 'APPLICATION_UPDATED'), (103, 'APPLICATION_DELETED'), (104, 'APPLICATION_ENABLED'), (105, 'APPLICATION_DISABLED'), (201, 'INVITATION_CREATED'), (202, 'INVITATION_SENT'), (203, 'INVITATION_ACCEPTED'), (601, 'MEMBERSHIP_CREATED'), (302, 'MEMBER_UPDATE_PROFILE'), (311, 'ADDRESS_CREATED'), (312, 'ADDRESS_UPDATED'), (313, 'ADDRESS_DELETED'), (314, 'ADDRESS_VERIFIED'), (401, 'ASSIGNMENT_CREATED'), (402, 'ASSIGNMENT_UPDATED'), (403, 'ASSIGNMENT_DELETED'), (505, 'SUBSCRIPTION_CREATED'), (506, 'SUBSCRIPTION_UPDATED'), (507, 'SUBSCRIPTION_DELETED'), (801, 'CHANNEL_CREATED'), (802, 'CHANNEL_UPDATED'), (803, 'CHANNEL_DELETED'), (804, 'CHANNEL_ENABLED'), (805, 'CHANNEL_DISABLED'), (806, 'CHANNEL_DEPRECATED'), (901, 'EVENT_CREATED'), (902, 'EVENT_UPDATED'), (903, 'EVENT_DELETED'), (904, 'EVENT_ENABLED'), (905, 'EVENT_DISABLED'), (906, 'EVENT_DEV_MODE_ON'), (907, 'EVENT_DEV_MODE_OFF')]),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=bitcaster.framework.db.fields.OrganizationRoleField(choices=[(-1, 'Superuser'), (1, 'Owner'), (2, 'Supervisor'), (4, 'Member')], default=4),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (20, 'Retry'), (21, 'Remind'), (22, 'Waiting confirmation'), (98, 'Address not confirmed'), (99, 'Expired'), (100, 'Complete'), (101, 'Confirmed')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_role',
            field=bitcaster.framework.db.fields.OrganizationRoleField(choices=[(-1, 'Superuser'), (1, 'Owner'), (2, 'Supervisor'), (4, 'Member')], default=4),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=bitcaster.framework.db.fields.OrganizationRoleField(choices=[(-1, 'Superuser'), (1, 'Owner'), (2, 'Supervisor'), (4, 'Member')], default=4),
        ),
    ]
