# Generated by Django 2.2.2 on 2019-06-09 18:51

from django.db import migrations

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0023_auto_20190609_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='context',
            field=bitcaster.framework.db.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
