# Generated by Django 5.2.16 on 2026-07-30 09:43

import smart_selects.db_fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0024_alter_apikey_grants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributionlist",
            name="application",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="project",
                chained_model_field="project",
                help_text="when set, the distribution list is pinned to this application",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bitcaster.application",
                verbose_name="Application",
            ),
        ),
    ]
