# Generated by Django 2.2.2 on 2019-06-09 20:10

from django.db import migrations

import bitcaster.framework.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcaster', '0024_occurence_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=bitcaster.framework.db.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
