# Generated by Django 5.2.16 on 2026-08-01 06:20

import concurrency.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0025_alter_distributionlist_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0,
                        help_text="version number of the record",
                        verbose_name="Version",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record last update time",
                        verbose_name="Last updated",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation time",
                        verbose_name="Created",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If the subscription is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment used to receive the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="bitcaster.assignment",
                        verbose_name="Assignment",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="Notification the user wants to listen to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="bitcaster.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
