# Generated by Django 5.2.16 on 2026-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0026_subscription"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("notification", "assignment"),
                name="bitcaster_subscription_notification_assignment",
            ),
        ),
    ]
