# Generated by Django 5.2.16 on 2026-08-02 09:39

import concurrency.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bitcaster.models.deliverysimulation
import bitcaster.models.eventsimulation


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0027_subscription_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0,
                        help_text="version number of the record",
                        verbose_name="Version",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record last update time",
                        verbose_name="Last updated",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation time",
                        verbose_name="Created",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sample context used for the simulation",
                        verbose_name="Context",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Options provided by the sender to route linked notifications",
                        verbose_name="Options",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fast", "Fast"),
                            ("full", "Full"),
                            ("partial", "Partial"),
                        ],
                        help_text="Depth of the simulation",
                        max_length=20,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=bitcaster.models.eventsimulation._status_choices,
                        default="NEW",
                        help_text="Status of the simulation",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Information about the processing (recipients, channels)",
                        verbose_name="Data",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when simulation has been created.",
                        verbose_name="Date",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="bitcaster.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event simulation",
                "verbose_name_plural": "Event simulations",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="DeliverySimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0,
                        help_text="version number of the record",
                        verbose_name="Version",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record last update time",
                        verbose_name="Last updated",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation time",
                        verbose_name="Created",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=bitcaster.models.deliverysimulation._status_choices,
                        default="NEW",
                        help_text="Status of the delivery",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Information about the delivery (rendered content, errors)",
                        verbose_name="Data",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment reached by this delivery",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_deliveries",
                        to="bitcaster.assignment",
                        verbose_name="Assignment",
                    ),
                ),
                (
                    "message_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message template used for the delivery, if any",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_deliveries",
                        to="bitcaster.messagetemplate",
                        verbose_name="Message template",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="Notification sent to the assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_deliveries",
                        to="bitcaster.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        help_text="Simulation this delivery belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bitcaster.eventsimulation",
                        verbose_name="Simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery simulation",
                "verbose_name_plural": "Delivery simulations",
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["simulation", "notification"],
                        name="delivery_simulation_sim_notif",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("simulation", "assignment", "notification"),
                        name="delivery_simulation_unique",
                    )
                ],
            },
        ),
    ]
