# Generated by Django 5.2.16 on 2026-08-02 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0028_eventsimulation_deliverysimulation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("trigger_event", "Can trigger event"),
                    ("debug_event", "Can debug event"),
                ),
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
