# Generated by Django 5.2.16 on 2026-08-03 12:34

import concurrency.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0029_alter_event_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0,
                        help_text="version number of the record",
                        verbose_name="Version",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record last update time",
                        verbose_name="Last updated",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation time",
                        verbose_name="Created",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("ERROR", "Error"),
                            ("FAILURE", "Failure"),
                        ],
                        default="PENDING",
                        help_text="Status of the delivery",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "errors",
                    models.IntegerField(
                        default=0,
                        help_text="Number of sending errors",
                        verbose_name="Errors",
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the next allowed sending attempt. Null means due immediately",
                        null=True,
                        verbose_name="Next attempt",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Information about the delivery (rendered content, errors)",
                        verbose_name="Data",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment that receives the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bitcaster.assignment",
                        verbose_name="Assignment",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Channel used to send the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bitcaster.channel",
                        verbose_name="Channel",
                    ),
                ),
                (
                    "message_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message template used for the delivery, if any",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bitcaster.messagetemplate",
                        verbose_name="Message template",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="Notification sent to the assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bitcaster.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        help_text="Occurrence this delivery belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bitcaster.occurrence",
                        verbose_name="Occurrence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="delivery_status_next_attempt",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("occurrence", "assignment", "notification", "channel"),
                        name="delivery_unique",
                    )
                ],
            },
        ),
    ]
