# Generated by Django 5.2.16 on 2026-08-04 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0031_add_occurrence_completed_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ("id",),
                "permissions": (("read_data", "Can read delivery data"),),
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
            },
        ),
    ]
