# Generated by Django 5.2.16 on 2026-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0032_add_delivery_read_data_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESSED", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="NEW",
                help_text="Status of the occurrence",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
