# Generated by Django 5.2.16 on 2026-08-13 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0035_applicationmembership_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="kind",
            field=models.CharField(
                choices=[("SERVER", "Server Key"), ("WEB", "Web Key")],
                default="SERVER",
                help_text="Server keys are used by backends. Web keys are meant to be embedded in web pages",
                max_length=20,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked the key is revoked and cannot be used",
                verbose_name="Active",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiration date. Expired keys are rejected by the API",
                null=True,
                verbose_name="Expires at",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp of the last successful authentication",
                null=True,
                verbose_name="Last used at",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="allowed_origins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                default=list,
                help_text=(
                    "Origins allowed to use this key (required for web keys). "
                    "Requests carrying an Origin header must match one of these values"
                ),
                null=True,
                size=None,
                verbose_name="Allowed origins",
            ),
        ),
    ]
