# Generated by Django 5.2.16 on 2026-08-13 12:00

import concurrency.fields
import smart_selects.db_fields

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bitcaster.models.key


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0036_apikey_kind_is_active_expires_at_last_used_at_allowed_origins"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="version number of the record", verbose_name="Version"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Record last update time", verbose_name="Last updated"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
                ),
                (
                    "token",
                    models.CharField(
                        default=bitcaster.models.key.make_token,
                        help_text="client token",
                        max_length=255,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user that owns this token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="api key that minted this token",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_tokens",
                        to="bitcaster.apikey",
                        verbose_name="Parent key",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="if set the token can only trigger this event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_tokens",
                        to="bitcaster.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "environments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20, null=True),
                        blank=True,
                        help_text="Limit validity to these environments. "
                        "If empty the token will be valid for any environment",
                        null=True,
                        size=None,
                        verbose_name="Environments",
                    ),
                ),
                (
                    "allowed_origins",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        help_text="Origins allowed to use this token. Requests without a matching Origin are rejected",
                        size=None,
                        verbose_name="Allowed origins",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration date",
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked the token is revoked and cannot be used",
                        verbose_name="Active",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp of the last successful authentication",
                        null=True,
                        verbose_name="Last used at",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="bitcaster.organization",
                    ),
                ),
                (
                    "project",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="organization",
                        chained_model_field="organization",
                        help_text="Project this record belong to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        show_all=False,
                        to="bitcaster.project",
                    ),
                ),
                (
                    "application",
                    smart_selects.db_fields.ChainedForeignKey(
                        blank=True,
                        chained_field="project",
                        chained_model_field="project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        show_all=False,
                        to="bitcaster.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Token",
                "verbose_name_plural": "Client Tokens",
                "ordering": ("-created",),
            },
        ),
    ]
