# Generated by Django 5.2.16 on 2026-08-13 12:30

from django.db import migrations, models

import bitcaster.models.key


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0037_clienttoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="grants",
            field=bitcaster.models.key.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FULL_ACCESS", "Full Access"),
                        ("SYSTEM_PING", "Ping"),
                        ("USER_READ", "User Read"),
                        ("USER_PROFILE", "Read User Profile and emssages"),
                        ("USER_WRITE", "User Write"),
                        ("ORG_READ", "Organization Read"),
                        ("APPLICATION_ADMIN", "Application Admin"),
                        ("EVENT_LIST", "Event list"),
                        ("EVENT_TRIGGER", "Event Trigger"),
                        ("EVENT_AUTO_CREATE", "Event Auto-Create"),
                        ("WEB_TRIGGER", "Web Event Trigger"),
                        ("DISTRIBUTION_LIST", "Distribution list"),
                        ("MANAGE_APPLICATION_USERS", "Manage Application Users"),
                    ],
                    max_length=255,
                ),
                blank=True,
                help_text="grants for this key",
                null=True,
                verbose_name="Grants",
            ),
        ),
    ]
