# Generated by Django 2.0.2 on 2018-03-02 12:54

import bitfield.models
import concurrency.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import mercury.fields
import mercury.file_storage
import mercury.models.user
import mercury.utils.tokens
import strategy_field.fields
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='full name')),
                ('friendly_name', models.CharField(blank=True, help_text='display/friendly name. Can be given name or nickname', max_length=250, verbose_name='display name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_managed', models.BooleanField(default=False, help_text='Designates whether this user should be treated as managed. Select this to disallow the user from modifying their account (username, password, etc).', verbose_name='managed')),
                ('is_password_expired', models.BooleanField(default=False, help_text='If set to true then the user needs to change the password on next sign in.', verbose_name='password expired')),
                ('last_password_change', models.DateTimeField(help_text='The date the password was changed last.', null=True, verbose_name='date of last password change')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('storage', mercury.fields.EncryptedJSONField(blank=True, help_text='Where store handler related user data', null=True, verbose_name='storage')),
                ('avatar', models.ImageField(blank=True, height_field='picture_height', null=True, storage=mercury.file_storage.MediaFileSystemStorage(), upload_to=mercury.file_storage._get_media_root, width_field='picture_width')),
                ('picture_height', models.IntegerField(editable=False, null=True)),
                ('picture_width', models.IntegerField(editable=False, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('language', mercury.fields.LanguageField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=5)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'permissions': (('activate_user', 'Can activate user'),),
            },
            managers=[
                ('objects', mercury.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=mercury.utils.tokens.generate_api_token, max_length=64, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiTriggerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=mercury.utils.tokens.generate_api_token, max_length=64, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator('^[\\w -]+$', 'Enter a valid name.', 'invalid')], verbose_name='Name')),
                ('slug', models.SlugField(blank=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('allowed_origins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('first_event', models.DateTimeField(editable=False, null=True)),
                ('rate_limit_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('rate_limit_window', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('flags', bitfield.models.BitField((), default=0, null=True)),
                ('avatar', models.ImageField(blank=True, height_field='picture_height', null=True, storage=mercury.file_storage.MediaFileSystemStorage(), upload_to=mercury.file_storage._get_media_root, width_field='picture_width')),
                ('picture_height', models.IntegerField(editable=False, null=True)),
                ('picture_width', models.IntegerField(editable=False, null=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('config', mercury.fields.EncryptedJSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('handler', strategy_field.fields.StrategyField(verbose_name='Dispatcher')),
                ('deprecated', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to='mercury.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('allowed_origins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('group', models.CharField(blank=True, max_length=30, null=True)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mercury.Application')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mercury.Application')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mercury.Channel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mercury.Event')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mercury.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('all', 'All'), ('it', 'Italian'), ('fr', 'French'), ('es', 'Spanish'), ('en', 'English')], default='all', max_length=3)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField()),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mercury.Application')),
                ('channels', models.ManyToManyField(related_name='messages', to='mercury.Channel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mercury.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submissions', models.IntegerField(default=0, help_text='number of subscriptions')),
                ('successes', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Visible'), (2, 'Pending Deletion'), (3, 'Deletion in Progress')], default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(blank=True, height_field='picture_height', null=True, storage=mercury.file_storage.MediaFileSystemStorage(), upload_to=mercury.file_storage._get_media_root, width_field='picture_width')),
                ('picture_height', models.IntegerField(editable=False, null=True)),
                ('picture_width', models.IntegerField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.IntegerField(choices=[(99, 'Owner'), (90, 'Admin'), (50, 'Member')], default=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mercury.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mercury.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', mercury.fields.EncryptedPickledObjectField(editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('config', mercury.fields.EncryptedJSONField(blank=True, null=True)),
                ('deactivation_token', models.CharField(editable=False, max_length=100, unique=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.Channel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mercury.Event')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mercury.User')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='mercury.OrganizationMember', to='mercury.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='mercury.User'),
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mercury.Organization'),
        ),
        migrations.AddField(
            model_name='apitriggerkey',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='mercury.Application'),
        ),
        migrations.AddField(
            model_name='apitriggerkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='mercury.User'),
        ),
        migrations.AddField(
            model_name='apiauthtoken',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mercury.Application'),
        ),
        migrations.AddField(
            model_name='apiauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mercury.User'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('channel', 'subscriber')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationoption',
            unique_together={('organization', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user'), ('organization', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('application', 'name')},
        ),
    ]
