from .. import env

AXES_ENABLED = env("AXES_ENABLED")
AXES_FAILURE_LIMIT = env.int("AXES_FAILURE_LIMIT")
AXES_COOLOFF_TIME = env.int("AXES_COOLOFF_TIME")
AXES_RESET_ON_SUCCESS = env.bool("AXES_RESET_ON_SUCCESS")
AXES_LOCKOUT_URL = env("AXES_LOCKOUT_URL")
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
