# Adds labels to pull requests for the type of change the PR makes
name: Adds labels

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  label-pullrequest:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    name: labels pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Add Migration label
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.changes.outputs.migrations == 'true'
        with:
          labels: 'Add/Change migration(s)'

      - name: Add Dependencies label
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          labels: 'Add/Change dependencies'

      - name: Code configuration settings
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.changes.outputs.code_settings == 'true'
        with:
          labels: 'Change Linters Configuration'

      - name: GitHub Configuration
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.changes.outputs.actions == 'true'
        with:
          labels: 'GitHub Actions'
